# -*- coding: utf-8 -*-
"""Dash_Source_Code (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypOR2-lbgxBfYvIKtA-3FatfVdt_RXER

# 🎷 New Orleans Climate-Aware Activity Recommender
> **Proposal Implementation** — Hongbo Zhang  
> Stack: Python · Dash · Plotly · Open-Meteo API

**How to use:**
1. Run **Step 1** to install packages  
2. Run **Step 2** to execute the ETL pipeline  
3. Run **Step 3** to launch the interactive Recommender App

## 📦 Step 1: Install Dependencies
"""

!pip install dash dash-bootstrap-components plotly pandas requests --quiet

"""## 🔑 Step 2a: Configure Supabase Connection"""

# ══════════════════════════════════════════════════════════════════════════════
# 🔑 SUPABASE CONNECTION SETUP
# ══════════════════════════════════════════════════════════════════════════════
# 1. Go to https://supabase.com → your project → Settings → Database
# 2. Copy the "Connection string" (URI format)
# 3. Paste it below replacing the placeholder

import os
os.environ["POSTGRES_URI"] = (
    "postgresql://postgres:20030419a@db.mgiwbojyhndygfpaisll.supabase.co:5432/postgres"
)

# ── OR leave blank to use API data only ──────────────────────────────────────
# os.environ["POSTGRES_URI"] = ""

print("✅ Environment set. Run the next cell to start the ETL pipeline.")

"""## 🔧 Step 2b: ETL Pipeline — Extract · Transform · Validate · Load to PostgreSQL"""

from __future__ import annotations
import logging, requests, os
import pandas as pd
from typing import Dict, List

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

# ══════════════════════════════════════════════════════════════════════════════
# SUPABASE / POSTGRESQL CONNECTION
# ══════════════════════════════════════════════════════════════════════════════
# Paste your Supabase connection string here:
# Format: postgresql://postgres:[PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres
POSTGRES_URI = os.getenv("POSTGRES_URI", "")  # or paste directly:
# POSTGRES_URI = "postgresql://postgres:YOUR_PASSWORD@db.xxxx.supabase.co:5432/postgres"

def get_db_engine():
    """Return SQLAlchemy engine if URI is set, else None."""
    if not POSTGRES_URI:
        return None
    try:
        from sqlalchemy import create_engine
        engine = create_engine(POSTGRES_URI, pool_pre_ping=True)
        with engine.connect() as conn:
            logger.info("✅ PostgreSQL connected successfully")
        return engine
    except Exception as e:
        logger.warning(f"⚠️  DB connection failed: {e}")
        return None

engine = get_db_engine()
USE_DB = engine is not None

# ══════════════════════════════════════════════════════════════════════════════
# COMPONENT 1: DATA EXTRACTION
# ══════════════════════════════════════════════════════════════════════════════
BASE_URL = "https://api.open-meteo.com/v1/forecast"

FORECAST_PARAMS = {
    "latitude": 29.9547, "longitude": -90.0751,
    "daily": [
        "temperature_2m_max","temperature_2m_min","temperature_2m_mean",
        "precipitation_sum","rain_sum","precipitation_probability_max",
        "windspeed_10m_max","windgusts_10m_max",
        "weathercode","cloudcover_mean","shortwave_radiation_sum",
    ],
    "temperature_unit": "fahrenheit",
    "windspeed_unit": "mph",
    "precipitation_unit": "inch",
    "timezone": "America/Chicago",
    "forecast_days": 16,
}

WMO_CODES = {
    0:"Clear sky", 1:"Mainly clear", 2:"Partly cloudy", 3:"Overcast",
    45:"Foggy", 48:"Icy fog",
    51:"Light drizzle", 53:"Moderate drizzle", 55:"Dense drizzle",
    61:"Slight rain", 63:"Moderate rain", 65:"Heavy rain",
    71:"Slight snow", 73:"Moderate snow", 75:"Heavy snow",
    80:"Slight showers", 81:"Moderate showers", 82:"Violent showers",
    95:"Thunderstorm", 96:"Thunderstorm w/ hail", 99:"Thunderstorm w/ heavy hail",
}
WMO_ICONS = {
    0:"☀️", 1:"🌤️", 2:"⛅", 3:"☁️", 45:"🌫️", 48:"🌫️",
    51:"🌦️", 53:"🌦️", 55:"🌧️", 61:"🌧️", 63:"🌧️", 65:"🌧️",
    71:"🌨️", 73:"🌨️", 75:"❄️", 80:"🌦️", 81:"🌦️", 82:"⛈️",
    95:"⛈️", 96:"⛈️", 99:"⛈️",
}

FALLBACK = {
    "daily": {
        "time":["2026-06-03","2026-06-04","2026-06-05","2026-06-06","2026-06-07",
                "2026-06-08","2026-06-09","2026-06-10","2026-06-11","2026-06-12",
                "2026-06-13","2026-06-14","2026-06-15","2026-06-16","2026-06-17","2026-06-18"],
        "temperature_2m_max":    [93,91,88,95,97,94,89,92,96,93,90,88,94,97,95,92],
        "temperature_2m_min":    [76,74,72,78,80,77,73,75,79,76,74,72,77,81,78,75],
        "temperature_2m_mean":   [84,82,80,86,88,85,81,83,87,84,82,80,85,89,86,83],
        "precipitation_sum":     [0.0,0.1,0.8,0.0,0.0,0.3,0.9,0.0,0.0,0.2,0.6,0.0,0.0,0.1,0.4,0.0],
        "rain_sum":              [0.0,0.1,0.8,0.0,0.0,0.3,0.9,0.0,0.0,0.2,0.6,0.0,0.0,0.1,0.4,0.0],
        "precipitation_probability_max":[5,20,75,5,10,40,80,10,5,30,70,5,5,25,55,10],
        "windspeed_10m_max":     [9,12,18,7,8,14,22,10,9,13,17,8,7,11,16,9],
        "windgusts_10m_max":     [15,20,28,12,14,22,35,17,15,21,26,14,12,18,25,15],
        "weathercode":           [1,2,61,0,1,80,63,1,0,2,61,1,0,2,80,1],
        "cloudcover_mean":       [20,45,85,10,25,60,90,30,15,50,80,20,10,40,70,25],
        "shortwave_radiation_sum":[22,18,9,25,23,15,7,20,24,17,10,22,25,19,12,21],
    }
}

# ══════════════════════════════════════════════════════════════════════════════
# COMPONENT 2: EXTRACT → TRANSFORM
# ══════════════════════════════════════════════════════════════════════════════
def extract() -> pd.DataFrame:
    """Try live API first; fallback to static dataset."""
    logger.info("Fetching 16-day forecast from Open-Meteo…")
    try:
        r = requests.get(BASE_URL, params=FORECAST_PARAMS, timeout=20)
        r.raise_for_status()
        data = r.json()
        logger.info("✅ Live API data retrieved")
    except Exception as e:
        logger.warning(f"⚠️  API failed ({e}), using fallback dataset")
        data = FALLBACK

    df = pd.DataFrame(data["daily"])
    df["date"] = pd.to_datetime(df["time"])
    return df.drop(columns=["time"]).set_index("date")


def transform(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy().rename(columns={
        "temperature_2m_max": "temp_max_f", "temperature_2m_min": "temp_min_f",
        "temperature_2m_mean": "temp_mean_f", "precipitation_sum": "precip_in",
        "rain_sum": "rain_in", "precipitation_probability_max": "precip_prob_pct",
        "windspeed_10m_max": "wind_max_mph", "windgusts_10m_max": "wind_gust_mph",
        "cloudcover_mean": "cloud_pct", "shortwave_radiation_sum": "solar_mj",
        "weathercode": "wmo_code",
    })
    for c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df["cloud_pct"]      = df["cloud_pct"].fillna(45)
    df["precip_in"]      = df["precip_in"].fillna(0)
    df["precip_prob_pct"]= df["precip_prob_pct"].fillna(0)
    df["weather_desc"]   = df["wmo_code"].map(WMO_CODES).fillna("Unknown")
    df["weather_icon"]   = df["wmo_code"].map(WMO_ICONS).fillna("🌡️")
    return df


def validate(df: pd.DataFrame) -> None:
    assert not df.empty
    assert (df["temp_max_f"] >= df["temp_min_f"]).all()
    logger.info(f"✅ Validation passed — {len(df)} forecast days")

# ══════════════════════════════════════════════════════════════════════════════
# COMPONENT 3: LOAD → POSTGRESQL (Supabase)
# ══════════════════════════════════════════════════════════════════════════════
def load_to_postgres(df: pd.DataFrame) -> None:
    """
    Write daily climate records to Supabase PostgreSQL.
    Maps to your schema: climate_data table.
    Uses INSERT ... ON CONFLICT DO UPDATE (upsert by location+date).
    """
    if not USE_DB:
        logger.info("No DB connection — skipping PostgreSQL load")
        return

    from sqlalchemy import text

    # Convert °F → °C for DB (schema uses Celsius)
    def f2c(f): return round((f - 32) * 5 / 9, 2)

    rows = []
    for date, row in df.iterrows():
        rows.append({
            "location_id":            1,
            "record_date":            date.strftime("%Y-%m-%d"),
            "temp_max":               f2c(row["temp_max_f"]),
            "temp_min":               f2c(row["temp_min_f"]),
            "temp_mean":              f2c(row["temp_mean_f"]),
            "precipitation_sum":      round(float(row["precip_in"]) * 25.4, 2),  # in→mm
            "rain_sum":               round(float(row["rain_in"])   * 25.4, 2),
            "snowfall_sum":           0.0,
            "humidity_max":           None,
            "humidity_min":           None,
            "humidity_mean":          None,
            "wind_speed_mean":        None,
            "wind_speed_max":         round(float(row["wind_max_mph"]) * 1.609, 2),  # mph→km/h
            "cloud_cover_mean":       float(row["cloud_pct"]),
            "shortwave_radiation_sum":float(row["solar_mj"]),
            "pressure_msl_mean":      None,
            "soil_moisture_mean":     None,
            "weather_code":           int(row["wmo_code"]) if pd.notna(row["wmo_code"]) else None,
        })

    with engine.begin() as conn:
        for r in rows:
            conn.execute(text("""
                INSERT INTO climate_data (
                    location_id, record_date,
                    temp_max, temp_min, temp_mean,
                    precipitation_sum, rain_sum, snowfall_sum,
                    humidity_max, humidity_min, humidity_mean,
                    wind_speed_mean, wind_speed_max,
                    cloud_cover_mean, shortwave_radiation_sum,
                    pressure_msl_mean, soil_moisture_mean, weather_code
                ) VALUES (
                    :location_id, :record_date,
                    :temp_max, :temp_min, :temp_mean,
                    :precipitation_sum, :rain_sum, :snowfall_sum,
                    :humidity_max, :humidity_min, :humidity_mean,
                    :wind_speed_mean, :wind_speed_max,
                    :cloud_cover_mean, :shortwave_radiation_sum,
                    :pressure_msl_mean, :soil_moisture_mean, :weather_code
                )
                ON CONFLICT (location_id, record_date)
                DO UPDATE SET
                    temp_max               = EXCLUDED.temp_max,
                    temp_min               = EXCLUDED.temp_min,
                    temp_mean              = EXCLUDED.temp_mean,
                    precipitation_sum      = EXCLUDED.precipitation_sum,
                    wind_speed_max         = EXCLUDED.wind_speed_max,
                    cloud_cover_mean       = EXCLUDED.cloud_cover_mean,
                    shortwave_radiation_sum= EXCLUDED.shortwave_radiation_sum,
                    weather_code           = EXCLUDED.weather_code,
                    fetched_at             = NOW()
            """), r)
    logger.info(f"✅ Loaded {len(rows)} rows → PostgreSQL climate_data")


def load_recommendations_to_postgres(rec_df: pd.DataFrame) -> None:
    """Write recommendation scores to Supabase recommendation table."""
    if not USE_DB:
        return

    from sqlalchemy import text

    with engine.begin() as conn:
        # Get climate_ids for matching dates
        id_map = pd.read_sql(
            "SELECT climate_id, record_date FROM climate_data WHERE location_id=1",
            conn
        )
        id_map["record_date"] = pd.to_datetime(id_map["record_date"])

        # Get activity_ids from DB
        act_map = pd.read_sql("SELECT activity_id, name FROM activity", conn)
        act_map["name_lower"] = act_map["name"].str.lower().str.strip()

        for date, row in rec_df.iterrows():
            recs = score_activities(row)
            climate_row = id_map[id_map["record_date"] == pd.Timestamp(date)]
            if climate_row.empty:
                continue
            climate_id = int(climate_row["climate_id"].values[0])

            for _, act in recs.iterrows():
                # Match activity name to DB
                match = act_map[act_map["name_lower"].str.contains(
                    act["name"].split()[0].lower(), na=False
                )]
                activity_id = int(match["activity_id"].values[0]) if not match.empty else 1

                conn.execute(text("""
                    INSERT INTO recommendation
                        (climate_id, activity_id, suitability_score, reason_summary)
                    VALUES
                        (:climate_id, :activity_id, :score, :reason)
                    ON CONFLICT DO NOTHING
                """), {
                    "climate_id":  climate_id,
                    "activity_id": activity_id,
                    "score":       float(act["score"]),
                    "reason":      act["name"] + " — " + act["description"],
                })

    logger.info("✅ Recommendations loaded → PostgreSQL")


def read_from_postgres() -> pd.DataFrame:
    """
    Pull climate data FROM Supabase using v_climate_summary view.
    Falls back to API data if DB unavailable.
    """
    if not USE_DB:
        logger.info("No DB — using API/fallback data")
        return None
    try:
        df = pd.read_sql("""
            SELECT
                record_date       AS date,
                temp_max          AS temp_max_c,
                temp_min          AS temp_min_c,
                temp_mean         AS temp_mean_c,
                -- convert back to °F for display
                temp_max * 9/5 + 32  AS temp_max_f,
                temp_min * 9/5 + 32  AS temp_min_f,
                temp_mean* 9/5 + 32  AS temp_mean_f,
                precipitation_sum / 25.4 AS precip_in,
                rain_sum / 25.4          AS rain_in,
                wind_speed_max / 1.609   AS wind_max_mph,
                cloud_cover_mean         AS cloud_pct,
                shortwave_radiation_sum  AS solar_mj,
                weather_description      AS weather_desc,
                icon_label               AS weather_icon_label,
                weather_code
            FROM v_climate_summary
            ORDER BY record_date
            LIMIT 16
        """, engine, parse_dates=["date"])
        df = df.set_index("date")
        # Map icon labels back to emoji
        df["weather_icon"] = df["weather_code"].map(WMO_ICONS).fillna("🌡️")
        df["precip_prob_pct"] = 30  # not stored in DB, use default
        logger.info(f"✅ Loaded {len(df)} rows from PostgreSQL")
        return df
    except Exception as e:
        logger.warning(f"⚠️  DB read failed: {e}")
        return None

# ══════════════════════════════════════════════════════════════════════════════
# RECOMMENDATION ENGINE
# ══════════════════════════════════════════════════════════════════════════════
ACTIVITY_CATALOGUE = [
    ("hike",     "Hiking & Nature Trails",     "Outdoor Sports",           "🥾",
     "City Park, Audubon Park, Barataria Preserve",
     50, 85,  0.10, 20, 50,   72, 20,  0.00, 8,  88),
    ("bike",     "Biking the Levee",           "Outdoor Sports",           "🚴",
     "Ride along the Mississippi River levee path",
     50, 88,  0.10, 18, 60,   74, 30,  0.00, 10, 85),
    ("kayak",    "Kayaking & Boating",         "Outdoor Sports",           "🛶",
     "Mississippi River & bayou kayak tours",
     60, 90,  0.00, 15, 60,   78, 25,  0.00, 7,  90),
    ("swamp",    "Swamp Tour",                 "Outdoor Sports",           "🐊",
     "Airboat swamp & wildlife tours",
     58, 92,  0.15, 18, 65,   80, 40,  0.05, 8,  87),
    ("parade",   "Street Parades & Festivals", "Weather-Dependent Events", "🎉",
     "French Quarter parades, Frenchmen St. events",
     55, 92,  0.15, 18, 65,   76, 35,  0.00, 8,  92),
    ("crawfish", "Crawfish Boil",              "Weather-Dependent Events", "🦐",
     "Outdoor boil gatherings, backyard parties",
     60, 90,  0.10, 20, 70,   78, 45,  0.00, 9,  88),
    ("festival", "Outdoor Music Festival",     "Weather-Dependent Events", "🎸",
     "Jazz Fest, Essence Fest, outdoor concerts",
     58, 90,  0.10, 18, 65,   76, 30,  0.00, 8,  90),
    ("rooftop",  "Rooftop Bars & Dining",      "Weather-Dependent Events", "🍹",
     "Rooftop venues with city skyline views",
     62, 90,  0.05, 15, 40,   77, 15,  0.00, 7,  86),
    ("museum",   "Museums & Art Galleries",    "Indoor Activities",        "🖼️",
     "NOMA, WWII Museum, Ogden Museum",
     -99, 999, 99, 99, 999,   80, 85,  0.50, 20, 78),
    ("jazz",     "Jazz Clubs & Live Music",    "Indoor Activities",        "🎷",
     "Frenchmen St. clubs, Preservation Hall",
     -99, 999, 99, 99, 999,   82, 80,  0.40, 18, 82),
    ("shop",     "Shopping & French Market",   "Indoor Activities",        "🛍️",
     "Royal St., Magazine St., French Market",
     -99, 999, 99, 99, 999,   78, 70,  0.30, 15, 72),
    ("dining",   "Fine Dining & Beignets",     "Indoor Activities",        "🍽️",
     "Brennan\'s, Café Du Monde, Commander\'s Palace",
     -99, 999, 99, 99, 999,   85, 75,  0.35, 16, 80),
    ("ghost",    "Ghost Tour (Evening)",       "Seasonal Activities",      "👻",
     "French Quarter haunted walking tour (7–10 pm)",
     55, 88,  0.10, 18, 90,   72, 55,  0.05, 8,  84),
    ("holiday",  "Holiday Events & Markets",   "Seasonal Activities",      "🎄",
     "Christmas on the Bayou, holiday light tours",
     35, 80,  0.20, 22, 90,   60, 40,  0.05, 8,  80),
]
ACT_COLS = [
    "id","name","category","emoji","description",
    "temp_min","temp_max","precip_max","wind_max","cloud_max",
    "ideal_temp","ideal_cloud","ideal_precip","ideal_wind","base_score",
]
activity_df = pd.DataFrame(ACTIVITY_CATALOGUE, columns=ACT_COLS)


def score_activities(row: pd.Series) -> pd.DataFrame:
    t  = float(row["temp_mean_f"])
    p  = float(row["precip_in"])
    w  = float(row["wind_max_mph"])
    c  = float(row["cloud_pct"])
    pp = float(row["precip_prob_pct"])
    results = []
    for _, act in activity_df.iterrows():
        if act["temp_min"] > -99:
            if not (act["temp_min"] <= t <= act["temp_max"]): continue
            if p > act["precip_max"] or w > act["wind_max"] or c > act["cloud_max"]: continue
        base          = float(act["base_score"])
        temp_penalty  = min(20, abs(t - float(act["ideal_temp"])) * 1.0)
        cloud_penalty = min(15, abs(c - float(act["ideal_cloud"])) * 0.20)
        precip_penalty= min(20, abs(p - float(act["ideal_precip"])) * 12)
        wind_penalty  = min(10, abs(w - float(act["ideal_wind"])) * 0.5)
        prob_penalty  = min(15, pp * 0.20) if act["temp_min"] > -99 else 0
        score = base - temp_penalty - cloud_penalty - precip_penalty - wind_penalty - prob_penalty
        results.append({**act.to_dict(), "score": round(max(0, min(100, score)), 1)})
    if not results:
        for _, act in activity_df[activity_df["category"] == "Indoor Activities"].iterrows():
            results.append({**act.to_dict(), "score": 55.0})
    return pd.DataFrame(results).sort_values("score", ascending=False)

# ══════════════════════════════════════════════════════════════════════════════
# RUN ETL PIPELINE
# ══════════════════════════════════════════════════════════════════════════════
# Step 1: Extract & Transform from API
raw_df   = extract()
clean_df = transform(raw_df)
validate(clean_df)

# Step 2: Try reading from PostgreSQL (overrides API data if available)
db_df = read_from_postgres()
if db_df is not None:
    clean_df = db_df
    logger.info("📦 Using PostgreSQL data for dashboard")
else:
    logger.info("📡 Using API/fallback data for dashboard")

# Step 3: Write to PostgreSQL
load_to_postgres(clean_df)
load_recommendations_to_postgres(clean_df)

DATES = clean_df.index.strftime("%Y-%m-%d").tolist()

# Weekly aggregation
weekly_df = clean_df.resample("W").agg(
    avg_temp_f=("temp_mean_f","mean"), max_temp_f=("temp_max_f","max"),
    min_temp_f=("temp_min_f","min"),   total_precip=("precip_in","sum"),
    avg_humidity=("precip_prob_pct","mean"), avg_wind_mph=("wind_max_mph","mean"),
    avg_cloud_pct=("cloud_pct","mean"), avg_solar_mj=("solar_mj","mean"),
).round(2)

print(f"\n{'='*60}")
print(f"  Data source : {'PostgreSQL (Supabase)' if USE_DB else 'API / Fallback'}")
print(f"  Forecast days: {len(clean_df)}")
print(f"  DB connected : {USE_DB}")
print(f"{'='*60}")
clean_df[["temp_mean_f","precip_in","wind_max_mph","cloud_pct","weather_desc"]].head(5)

"""## 🎷 Step 3: Launch the Interactive Recommender App"""

from dash import Dash, dcc, html, Input, Output, State, ctx, ALL, dash_table
import dash_bootstrap_components as dbc
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

# ── Design tokens ─────────────────────────────────────────────────────────────
C = {
    "bg":      "#f5f3ef",   # warm cream white
    "surface": "#ede9e1",   # slightly darker cream
    "card":    "#ffffff",   # pure white card
    "border":  "#d6cfc4",   # warm grey border
    "gold":    "#b8860b",   # dark gold (readable on light bg)
    "teal":    "#0d7a74",   # deep teal
    "coral":   "#c0392b",   # deep coral-red
    "sky":     "#2563eb",   # rich blue
    "green":   "#16a34a",   # forest green
    "text":    "#1a1208",   # near-black warm
    "muted":   "#6b5e4e",   # warm brown-grey
    "purple":  "#6d28d9",   # deep purple
    "orange":  "#c2410c",   # burnt orange
}
CARD = {
    "background":   C["card"],
    "borderRadius": "14px",
    "padding":      "20px",
    "border":       "1px solid " + C["border"],
    "marginBottom": "14px",
    "boxShadow":    "0 2px 12px rgba(0,0,0,0.07)",
}
CAT_COLOR = {
    "Outdoor Sports":           C["teal"],
    "Weather-Dependent Events": C["gold"],
    "Indoor Activities":        C["purple"],
    "Seasonal Activities":      C["coral"],
}
def score_color(s):
    return C["green"] if s >= 75 else C["gold"] if s >= 50 else C["coral"]

# ── Pre-compute all-days score matrix for charts ──────────────────────────────
all_scores = []
for d in DATES:
    row = clean_df.loc[d]
    recs = score_activities(row)
    for _, r in recs.iterrows():
        all_scores.append({"date": d, "name": r["name"],
                            "category": r["category"], "score": r["score"]})
scores_df = pd.DataFrame(all_scores)

# Best day per activity
best_days = scores_df.loc[scores_df.groupby("name")["score"].idxmax()][
    ["name","category","date","score"]].sort_values("score", ascending=False)

# Daily best outdoor score + summary for "Best Days" tab
daily_summary = []
for d in DATES:
    row = clean_df.loc[d]
    recs = score_activities(row)
    outdoor = recs[recs["category"] != "Indoor Activities"]
    top = recs.iloc[0] if not recs.empty else None
    daily_summary.append({
        "date":        d,
        "label":       pd.Timestamp(d).strftime("%a %b %d"),
        "temp_mean":   row["temp_mean_f"],
        "precip":      row["precip_in"],
        "wind":        row["wind_max_mph"],
        "cloud":       row["cloud_pct"],
        "top_activity":top["name"] if top is not None else "—",
        "top_score":   top["score"] if top is not None else 0,
        "outdoor_count": len(outdoor),
        "weather_icon":  row["weather_icon"],
        "weather_desc":  row["weather_desc"],
    })
summary_df = pd.DataFrame(daily_summary)

# ── Shared helpers ────────────────────────────────────────────────────────────
def _stat(label, value, color):
    return html.Div([
        html.Div(label, style={"color": C["muted"], "fontSize": "11px"}),
        html.Div(value, style={"color": color, "fontSize": "18px",
                               "fontWeight": "700", "fontFamily": "Playfair Display, serif"}),
    ], style={"background": C["bg"], "borderRadius": "8px", "padding": "10px 12px"})


def _landmark(emoji, name, desc):
    return html.Div([
        html.Span(emoji, style={"fontSize": "18px", "marginRight": "8px"}),
        html.Div([
            html.Div(name, style={"color": C["text"], "fontSize": "12px", "fontWeight": "600"}),
            html.Div(desc, style={"color": C["muted"], "fontSize": "11px"}),
        ]),
    ], style={
        "display": "flex", "alignItems": "center",
        "background": C["bg"], "borderRadius": "8px", "padding": "8px 10px",
    })

def weather_card(date_str):
    row = clean_df.loc[date_str]
    return html.Div([
        html.Div([
            html.Span(row["weather_icon"], style={"fontSize": "48px"}),
            html.Div(row["weather_desc"],
                     style={"color": C["text"], "fontWeight": "600",
                            "fontSize": "16px", "marginTop": "6px"}),
        ], style={"textAlign": "center", "marginBottom": "16px"}),
        html.Div([
            _stat("High",       str(int(row["temp_max_f"])) + " °F",     C["coral"]),
            _stat("Low",        str(int(row["temp_min_f"])) + " °F",     C["sky"]),
            _stat("Rain",       str(round(float(row["precip_in"]),2)) + " in", C["teal"]),
            _stat("Rain Prob",  str(int(row["precip_prob_pct"])) + " %", C["sky"]),
            _stat("Wind Max",   str(int(row["wind_max_mph"])) + " mph",  C["gold"]),
            _stat("Cloud",      str(int(row["cloud_pct"])) + " %",       C["muted"]),
        ], style={"display": "grid", "gridTemplateColumns": "1fr 1fr", "gap": "10px"}),
    ])

# ── Real photo URLs per activity (Unsplash direct links, no API key needed) ──
# Each activity: photos (2-3), intro, price range, Google Maps rating
ACTIVITY_META = {
    "hike": {
        "photos": [
            "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&q=80",
            "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=700&q=80",
            "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=700&q=80",
        ],
        "intro": "Explore lush trails through City Park's ancient oaks, Audubon Park's scenic paths, or the wild Barataria Preserve bayou walks. Perfect for nature lovers craving a peaceful escape from the city buzz.",
        "price": "Free – $5",
        "rating": 4.7,
    },
    "bike": {
        "photos": [
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=80",
            "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=700&q=80",
            "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=700&q=80",
        ],
        "intro": "Glide along the historic Mississippi River levee with panoramic views of the great river and the city skyline. Rent bikes near Audubon Park and cruise Magazine Street's colorful boutiques.",
        "price": "$15 – $30 rental",
        "rating": 4.6,
    },
    "kayak": {
        "photos": [
            "https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=700&q=80",
            "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=700&q=80",
            "https://images.unsplash.com/photo-1520390138845-fd2d229dd553?w=700&q=80",
        ],
        "intro": "Paddle through the serene bayous and cypress swamps surrounding New Orleans. Guided tours take you past Spanish moss-draped trees and local wildlife including herons, turtles, and alligators.",
        "price": "$45 – $85 guided",
        "rating": 4.8,
    },
    "swamp": {
        "photos": [
            "https://images.unsplash.com/photo-1504450874802-0ba2bcd9b5ae?w=700&q=80",
            "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=700&q=80",
            "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=700&q=80",
        ],
        "intro": "Zoom through the Louisiana wetlands on an airboat, spotting American alligators up close. Experienced Cajun guides share fascinating stories of swamp ecology, folklore, and survival skills.",
        "price": "$25 – $60",
        "rating": 4.7,
    },
    "parade": {
        "photos": [
            "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=700&q=80",
            "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=700&q=80",
            "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=700&q=80",
        ],
        "intro": "New Orleans parades are legendary — brass bands, second-line dancing, colorful floats, and throws from Mardi Gras krewes. Frenchmen Street comes alive nightly with spontaneous street performances.",
        "price": "Free",
        "rating": 4.9,
    },
    "crawfish": {
        "photos": [
            "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=700&q=80",
            "https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=700&q=80",
            "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=700&q=80",
        ],
        "intro": "A true Louisiana tradition — friends gather around newspaper-covered tables piled high with boiled crawfish seasoned with Cajun spice, corn, and potatoes. Find boils at local backyards and restaurants.",
        "price": "$15 – $35 per person",
        "rating": 4.8,
    },
    "festival": {
        "photos": [
            "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=700&q=80",
            "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=700&q=80",
            "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=700&q=80",
        ],
        "intro": "New Orleans Jazz & Heritage Festival draws world-class musicians every spring. Essence Fest lights up the Superdome in summer. Year-round outdoor stages at Woldenberg Park and Jackson Square.",
        "price": "$50 – $150 ticketed",
        "rating": 4.9,
    },
    "rooftop": {
        "photos": [
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80",
            "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=700&q=80",
            "https://images.unsplash.com/photo-1414609245224-aea2e1d3a2dc?w=700&q=80",
        ],
        "intro": "Sip craft cocktails with sweeping views of the French Quarter rooftops and the mighty Mississippi. Top spots include Rooftop at the Pontchartrain Hotel and Alto at the Ace Hotel.",
        "price": "$12 – $20 per cocktail",
        "rating": 4.6,
    },
    "museum": {
        "photos": [
            "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=700&q=80",
            "https://images.unsplash.com/photo-1565060169061-32a8a61e4e96?w=700&q=80",
            "https://images.unsplash.com/photo-1515169067868-5387ec356754?w=700&q=80",
        ],
        "intro": "The National WWII Museum is one of America's finest history museums. NOMA houses an impressive art collection spanning 5,000 years. The Ogden Museum celebrates Southern art and culture beautifully.",
        "price": "$15 – $30 admission",
        "rating": 4.8,
    },
    "jazz": {
        "photos": [
            "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=700&q=80",
            "https://images.unsplash.com/photo-1524650359799-842906ca1c06?w=700&q=80",
            "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=700&q=80",
        ],
        "intro": "Frenchmen Street is the soul of New Orleans live music — every night, world-class jazz, blues, and funk spill from club doorways. Preservation Hall on St. Peter St. is a must-visit jazz institution.",
        "price": "$5 – $25 cover",
        "rating": 4.9,
    },
    "shop": {
        "photos": [
            "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=700&q=80",
            "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=700&q=80",
            "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=700&q=80",
        ],
        "intro": "Magazine Street stretches 6 miles of boutiques, antique shops, and local galleries. The French Market offers hot sauce, pralines, and handmade crafts. Royal Street gleams with fine art and antiques.",
        "price": "Free to browse",
        "rating": 4.5,
    },
    "dining": {
        "photos": [
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=700&q=80",
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=700&q=80",
            "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=700&q=80",
        ],
        "intro": "New Orleans is a culinary paradise. Start your morning with beignets and café au lait at Café Du Monde. Splurge on Commander's Palace or Brennan's for legendary Creole cuisine in a stunning garden setting.",
        "price": "$15 – $80+ per person",
        "rating": 4.8,
    },
    "ghost": {
        "photos": [
            "https://images.unsplash.com/photo-1509557965875-b88c97052f0e?w=700&q=80",
            "https://images.unsplash.com/photo-1508361001413-7a9dca21d08a?w=700&q=80",
            "https://images.unsplash.com/photo-1572204292164-b35ba943fca7?w=700&q=80",
        ],
        "intro": "The French Quarter's dark past comes alive on guided ghost tours through haunted mansions, voodoo history, and vampire legends. Evening walks through flickering gas-lit streets are hauntingly unforgettable.",
        "price": "$20 – $35",
        "rating": 4.6,
    },
    "holiday": {
        "photos": [
            "https://images.unsplash.com/photo-1543589923-609b2a3d6299?w=700&q=80",
            "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=700&q=80",
            "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?w=700&q=80",
        ],
        "intro": "Christmas in New Orleans is magical — bonfires on the levee, caroling in Jackson Square, and holiday lights reflecting on the Mississippi. The Celebration in the Oaks transforms City Park into a winter wonderland.",
        "price": "$5 – $25",
        "rating": 4.7,
    },
}
# Legacy single-photo dict for backwards compat
ACTIVITY_PHOTOS = {k: v["photos"][0] for k, v in ACTIVITY_META.items()}


def rec_card(act, show_click_hint=True):
    s = act["score"]; cat = act["category"]; aid = act["id"]
    col = score_color(s)
    return html.Div([
        html.Div([
            html.Span(act["emoji"], style={"fontSize": "28px", "marginRight": "10px"}),
            html.Div([
                html.Div(act["name"], style={"color": C["text"], "fontWeight": "600", "fontSize": "15px"}),
                html.Div(act["description"], style={"color": C["muted"], "fontSize": "12px", "marginTop": "2px"}),
            ], style={"flex": "1"}),
            html.Div([
                html.Div(str(int(s)), style={"color": col, "fontSize": "22px", "fontWeight": "700",
                                              "fontFamily": "Playfair Display, serif", "textAlign": "right"}),
                html.Div("score", style={"color": C["muted"], "fontSize": "10px", "textAlign": "right"}),
            ]),
        ], style={"display": "flex", "alignItems": "center"}),
        html.Div([
            html.Div(cat, style={
                "display": "inline-block", "padding": "2px 10px",
                "borderRadius": "20px", "fontSize": "11px", "fontWeight": "600",
                "background": CAT_COLOR.get(cat, "#555") + "22",
                "color": CAT_COLOR.get(cat, "#aaa"),
                "border": "1px solid " + CAT_COLOR.get(cat, "#555") + "44",
            }),
            html.Div("📷 view photo", style={
                "fontSize": "10px", "color": C["muted"],
                "marginLeft": "auto", "opacity": "0.6",
            }) if show_click_hint else html.Div(),
        ], style={"display": "flex", "alignItems": "center", "marginTop": "8px"}),
    ],
        id={"type": "rec-card", "index": aid},
        n_clicks=0,
        style={
            "background": C["bg"], "borderRadius": "12px", "padding": "14px 16px",
            "border": "1px solid " + C["border"], "marginBottom": "10px",
            "borderLeft": "3px solid " + score_color(s),
            "cursor": "pointer", "transition": "border-color .2s",
        },
    )

def date_btn(d, active=False):
    dt = pd.Timestamp(d)
    bg     = "rgba(184,134,11,0.2)" if active else C["bg"]
    border = ("2px solid " + C["gold"]) if active else ("1px solid " + C["border"])
    return html.Button([
        html.Div(dt.strftime("%a"),  style={"fontSize": "11px", "color": C["muted"], "marginBottom": "2px"}),
        html.Div(dt.strftime("%d"),  style={"fontSize": "18px", "fontWeight": "700", "color": C["text"]}),
        html.Div(dt.strftime("%b"),  style={"fontSize": "11px", "color": C["muted"]}),
        html.Div(clean_df.loc[d, "weather_icon"], style={"fontSize": "18px", "marginTop": "4px"}),
    ], id={"type": "date-btn", "index": d}, n_clicks=0,
    style={"background": bg, "border": border, "borderRadius": "10px",
           "padding": "8px 6px", "cursor": "pointer", "textAlign": "center",
           "minWidth": "54px", "transition": "all .2s"})

def overview_fig(selected_date=None):
    dates = [pd.Timestamp(d).strftime("%b %d") for d in DATES]
    fig = go.Figure()
    fig.add_trace(go.Bar(x=dates, y=clean_df["precip_in"].values, name="Precip (in)",
                         yaxis="y2", marker_color="rgba(37,99,235,0.45)", width=0.4))
    fig.add_trace(go.Scatter(x=dates, y=clean_df["temp_max_f"].values, name="High °F",
                             line=dict(color=C["coral"], width=2), mode="lines+markers", marker=dict(size=5)))
    fig.add_trace(go.Scatter(x=dates, y=clean_df["temp_min_f"].values, name="Low °F",
                             line=dict(color=C["sky"], width=2, dash="dot"),
                             mode="lines+markers", marker=dict(size=5),
                             fill="tonexty", fillcolor="rgba(96,165,250,0.09)"))
    if selected_date and selected_date in DATES:
        fig.add_vline(x=DATES.index(selected_date), line_color=C["gold"], line_dash="dot", line_width=2)
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=C["muted"], size=11), margin=dict(l=10, r=10, t=10, b=10), height=220,
        legend=dict(orientation="h", y=1.12, bgcolor="rgba(0,0,0,0)", font=dict(size=10)),
        xaxis=dict(gridcolor=C["border"], showgrid=True, zeroline=False),
        yaxis=dict(gridcolor=C["border"], showgrid=True, zeroline=False, title="°F"),
        yaxis2=dict(overlaying="y", side="right", showgrid=False, title="Precip in", range=[0, 5]),
        hovermode="x unified",
    )
    return fig

# ── TAB 2: Climate Data table + stats ────────────────────────────────────────
table_df = clean_df.reset_index().rename(columns={
    "date": "Date", "temp_max_f": "High °F", "temp_min_f": "Low °F",
    "temp_mean_f": "Mean °F", "precip_in": "Precip in",
    "precip_prob_pct": "Rain Prob %", "wind_max_mph": "Wind mph",
    "cloud_pct": "Cloud %", "solar_mj": "Solar MJ",
    "weather_desc": "Condition", "weather_icon": "Icon",
})
table_df["Date"] = table_df["Date"].dt.strftime("%a %b %d")
table_cols = ["Date","Icon","Condition","High °F","Low °F","Mean °F",
              "Precip in","Rain Prob %","Wind mph","Cloud %","Solar MJ"]

def kpi(label, value, color):
    return html.Div([
        html.Div(label, style={"color": C["muted"], "fontSize": "11px",
                               "textTransform": "uppercase", "letterSpacing": "1px"}),
        html.Div(value, style={"color": color, "fontSize": "26px",
                               "fontWeight": "700", "fontFamily": "Playfair Display, serif",
                               "marginTop": "4px"}),
    ], style={**CARD, "flex": "1", "minWidth": "130px", "marginBottom": "0"})

stats_row = html.Div([
    kpi("Avg High Temp",   str(round(clean_df["temp_max_f"].mean(), 1)) + " °F", C["coral"]),
    kpi("Avg Low Temp",    str(round(clean_df["temp_min_f"].mean(), 1)) + " °F", C["sky"]),
    kpi("Total Precip",    str(round(clean_df["precip_in"].sum(), 2)) + " in",   C["teal"]),
    kpi("Rainy Days",      str((clean_df["precip_in"] > 0).sum()),                C["sky"]),
    kpi("Avg Wind",        str(round(clean_df["wind_max_mph"].mean(), 1)) + " mph", C["gold"]),
    kpi("Avg Cloud Cover", str(round(clean_df["cloud_pct"].mean(), 0)) + " %",   C["muted"]),
], style={"display": "flex", "gap": "12px", "flexWrap": "wrap", "marginBottom": "14px"})

climate_table = dash_table.DataTable(
    id="climate-table",
    columns=[{"name": c, "id": c} for c in table_cols],
    data=table_df[table_cols].to_dict("records"),
    style_table={
        "overflowX": "auto",
        "overflowY": "auto",
        "maxHeight": "420px",       # vertical scroll
        "borderRadius": "8px",
        "minWidth":  "100%",
    },
    fixed_rows={"headers": True},   # freeze header when scrolling
    style_header={
        "backgroundColor": C["surface"], "color": C["gold"],
        "fontWeight": "700", "border": "1px solid " + C["border"],
        "fontSize": "12px", "textAlign": "center",
        "position": "sticky", "top": "0", "zIndex": "1",
    },
    style_cell={
        "backgroundColor": C["bg"], "color": C["text"],
        "border": "1px solid " + C["border"], "fontSize": "12px",
        "textAlign": "center", "padding": "8px 12px",
        "fontFamily": "Inter, sans-serif", "minWidth": "80px",
    },
    style_data_conditional=[
        {"if": {"row_index": "odd"}, "backgroundColor": C["card"]},
        {"if": {"filter_query": "{Precip in} > 0.2"},
         "color": C["sky"], "fontWeight": "600"},
        {"if": {"filter_query": "{High °F} > 90"},
         "color": C["coral"], "fontWeight": "600"},
    ],
    sort_action="native",
    filter_action="native",         # built-in column filter
    page_action="none",             # show all rows (scroll instead of paginate)
    tooltip_delay=0,
    tooltip_duration=None,
)

# ── TAB 3: Charts ─────────────────────────────────────────────────────────────
def temp_range_fig():
    dates = [pd.Timestamp(d).strftime("%b %d") for d in DATES]
    fig = go.Figure()
    fig.add_trace(go.Bar(name="Temp Range",
                         x=dates,
                         y=clean_df["temp_max_f"].values - clean_df["temp_min_f"].values,
                         base=clean_df["temp_min_f"].values,
                         marker_color=C["coral"], opacity=0.8))
    fig.add_trace(go.Scatter(x=dates, y=clean_df["temp_mean_f"].values,
                             name="Mean Temp", mode="lines+markers",
                             line=dict(color=C["gold"], width=2), marker=dict(size=6)))
    fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      font=dict(color=C["muted"], size=11), height=280,
                      margin=dict(l=10,r=10,t=30,b=10),
                      title=dict(text="Daily Temperature Range (°F)", font=dict(color=C["text"])),
                      legend=dict(bgcolor="rgba(0,0,0,0)"),
                      xaxis=dict(gridcolor=C["border"]), yaxis=dict(gridcolor=C["border"]))
    return fig

def precip_fig():
    dates = [pd.Timestamp(d).strftime("%b %d") for d in DATES]
    fig = go.Figure()
    fig.add_trace(go.Bar(x=dates, y=clean_df["precip_in"].values,
                         name="Precipitation (in)", marker_color=C["sky"], opacity=0.85))
    fig.add_trace(go.Scatter(x=dates, y=clean_df["precip_prob_pct"].values,
                             name="Rain Probability %", yaxis="y2",
                             line=dict(color=C["teal"], width=2, dash="dot"),
                             mode="lines+markers", marker=dict(size=5)))
    fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      font=dict(color=C["muted"], size=11), height=280,
                      margin=dict(l=10,r=10,t=30,b=10),
                      title=dict(text="Precipitation & Rain Probability", font=dict(color=C["text"])),
                      legend=dict(bgcolor="rgba(0,0,0,0)"),
                      xaxis=dict(gridcolor=C["border"]),
                      yaxis=dict(gridcolor=C["border"], title="inches"),
                      yaxis2=dict(overlaying="y", side="right", title="%", showgrid=False),
                      hovermode="x unified")
    return fig

def calendar_heatmap_fig():
    """
    Calendar-style heatmap: each cell = one day, color = top activity comfort score.
    Rows = week number, Columns = day of week (Mon–Sun).
    """
    import math

    dates_ts  = [pd.Timestamp(d) for d in DATES]
    scores    = summary_df["top_score"].values
    labels    = summary_df["top_activity"].values
    icons     = [clean_df.loc[d, "weather_icon"] for d in DATES]
    day_names = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

    # Map each date to (week_row, dow_col)
    first_dow = dates_ts[0].dayofweek   # 0=Mon
    cells = []
    for i, (ts, sc, act, icon) in enumerate(zip(dates_ts, scores, labels, icons)):
        col = ts.dayofweek              # 0=Mon … 6=Sun
        row = (i + first_dow) // 7
        cells.append(dict(
            x=col, y=row,
            score=sc, activity=act,
            icon=icon,
            label=ts.strftime("%b %d"),
            dow=day_names[col],
        ))
    cells_df = pd.DataFrame(cells)
    n_weeks  = cells_df["y"].max() + 1

    # Build grid arrays
    z    = [[None]*7 for _ in range(n_weeks)]
    text = [["" ]*7 for _ in range(n_weeks)]
    hover= [["" ]*7 for _ in range(n_weeks)]
    for _, c in cells_df.iterrows():
        r, col = int(c["y"]), int(c["x"])
        z[r][col]    = c["score"]
        text[r][col] = f"{c['icon']}<br>{c['label']}<br>{int(c['score'])}"
        hover[r][col]= (f"<b>{c['label']} ({c['dow']})</b><br>"
                        f"Top activity: {c['activity']}<br>"
                        f"Score: {int(c['score'])}<extra></extra>")

    fig = go.Figure(go.Heatmap(
        z=z, x=day_names,
        y=[f"Week {i+1}" for i in range(n_weeks)],
        colorscale=[
            [0.0,  "#1e2535"],
            [0.35, C["coral"]],
            [0.60, C["orange"]],
            [0.80, C["gold"]],
            [1.0,  C["green"]],
        ],
        text=text, texttemplate="%{text}",
        textfont=dict(size=11, color="white"),
        customdata=hover,
        hovertemplate="%{customdata}",
        colorbar=dict(
            title="Comfort<br>Score",
            tickfont=dict(color=C["muted"]),
            tickvals=[0,40,60,75,90,100],
            ticktext=["0","40","60","75","90","100"],
        ),
        zmin=0, zmax=100,
        xgap=6, ygap=6,
    ))
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=C["muted"], size=11),
        height=80 + n_weeks * 110,
        margin=dict(l=10,r=10,t=50,b=10),
        title=dict(text="📅 16-Day Comfort Calendar — Top Activity Score per Day",
                   font=dict(color=C["text"], size=13)),
        xaxis=dict(side="top", tickfont=dict(color=C["gold"], size=12)),
        yaxis=dict(autorange="reversed", tickfont=dict(color=C["muted"])),
    )
    return fig

def heat_index_fig():
    """
    Heat Index (体感温度) — simplified NOAA formula.
    Uses mean temp + estimated humidity from cloud/precip proxy.
    Clamps output to realistic range [temp, temp+30].
    """
    dates = [pd.Timestamp(d).strftime("%b %d") for d in DATES]
    T  = clean_df["temp_mean_f"].values.astype(float)   # use mean, not max

    # Estimate humidity: New Orleans avg ~75%, higher on rainy days
    RH = []
    for _, row in clean_df.iterrows():
        base = 75.0
        if row["precip_in"] > 0.3:  base = 88.0
        elif row["precip_in"] > 0:  base = 82.0
        elif row["cloud_pct"] > 70: base = 80.0
        elif row["cloud_pct"] < 30: base = 68.0
        RH.append(base)
    RH = [float(r) for r in RH]

    def heat_index(t, rh):
        """Simple NWS heat index — valid for T>=80°F, RH>=40%."""
        if t < 80:
            return t   # below 80°F, HI ≈ actual temp
        hi = (-42.379
              + 2.04901523 * t
              + 10.14333127 * rh
              - 0.22475541 * t * rh
              - 0.00683783 * t * t
              - 0.05481717 * rh * rh
              + 0.00122874 * t * t * rh
              + 0.00085282 * t * rh * rh
              - 0.00000199 * t * t * rh * rh)
        # Clamp: HI should not exceed actual temp + 30°F (sanity check)
        return min(hi, t + 30)

    hi_vals = [round(heat_index(t, rh), 1) for t, rh in zip(T, RH)]

    # Dynamic y-axis range
    y_max = max(max(hi_vals) + 8, 105)
    y_min = min(min(T) - 5, 75)

    zone_colors = []
    for v in hi_vals:
        if v >= 103:  zone_colors.append(C["coral"])
        elif v >= 90: zone_colors.append(C["orange"])
        elif v >= 80: zone_colors.append(C["gold"])
        else:         zone_colors.append(C["green"])

    fig = go.Figure()

    # Colored danger band backgrounds
    fig.add_hrect(y0=103, y1=y_max, fillcolor=C["coral"],  opacity=0.12, line_width=0)
    fig.add_hrect(y0=90,  y1=103,   fillcolor=C["orange"], opacity=0.12, line_width=0)
    fig.add_hrect(y0=80,  y1=90,    fillcolor=C["gold"],   opacity=0.10, line_width=0)
    fig.add_hrect(y0=y_min, y1=80,  fillcolor=C["green"],  opacity=0.07, line_width=0)

    # Actual temp line
    fig.add_trace(go.Scatter(
        x=dates, y=T.tolist(), name="Actual Mean °F",
        line=dict(color=C["muted"], width=1.5, dash="dot"),
        mode="lines", opacity=0.7,
    ))
    # Feels-like line
    fig.add_trace(go.Scatter(
        x=dates, y=hi_vals, name="Feels Like °F",
        mode="lines+markers",
        line=dict(color=C["coral"], width=2.5),
        marker=dict(size=9, color=zone_colors,
                    line=dict(color="white", width=1.5)),
        hovertemplate=(
            "<b>%{x}</b><br>"
            "Feels like: <b>%{y:.1f}°F</b><extra></extra>"
        ),
    ))

    # Zone label annotations (right side)
    for y, label, col in [
        (max(y_max - 4, 106), "🔴 Extreme Danger ≥103°F", C["coral"]),
        (96,  "🟠 Danger 90–103°F",   C["orange"]),
        (85,  "🟡 Caution 80–90°F",   C["gold"]),
        (70,  "🟢 Comfortable <80°F",     C["green"]),
    ]:
        fig.add_annotation(x=dates[-1], y=y, text=label, showarrow=False,
                           xanchor="right", font=dict(size=9, color=col))

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=C["muted"], size=11), height=300,
        margin=dict(l=10,r=10,t=40,b=10),
        title=dict(text="🌡️ Heat Index — Feels Like Temperature (°F)",
                   font=dict(color=C["text"], size=13)),
        legend=dict(bgcolor="rgba(0,0,0,0)", orientation="h", y=1.12),
        xaxis=dict(gridcolor=C["border"], showgrid=True),
        yaxis=dict(gridcolor=C["border"], showgrid=True, title="°F", range=[50, 130]),
        hovermode="x unified",
    )
    return fig

# ── TAB 4: Best Days ──────────────────────────────────────────────────────────
def best_days_fig(selected_date=None):
    top = summary_df.sort_values("top_score", ascending=True).tail(16)

    sel_label = pd.Timestamp(selected_date).strftime("%a %b %d") if selected_date else None

    # Base color by score; selected → white border + brighter
    colors, borders, widths, opacities = [], [], [], []
    for _, row in top.iterrows():
        is_sel = (row["label"] == sel_label)
        colors.append(C["gold"] if is_sel else score_color(row["top_score"]))
        borders.append("white" if is_sel else "rgba(0,0,0,0)")
        widths.append(2.5 if is_sel else 0)
        opacities.append(1.0 if is_sel else (0.4 if sel_label else 1.0))

    fig = go.Figure(go.Bar(
        x=top["top_score"], y=top["label"], orientation="h",
        marker=dict(
            color=colors,
            opacity=opacities,
            line=dict(color=borders, width=widths),
        ),
        text=top["top_activity"],
        textposition="inside", insidetextanchor="middle",
        textfont=dict(color="white", size=11),
        hovertemplate="<b>%{y}</b><br>Top: %{text}<br>Score: %{x:.0f}<extra></extra>",
    ))

    # Add star annotation on selected bar
    if sel_label and sel_label in top["label"].values:
        sel_score = top.loc[top["label"] == sel_label, "top_score"].values[0]
        fig.add_annotation(
            x=sel_score + 2, y=sel_label,
            text="★ Selected",
            showarrow=False,
            font=dict(color=C["gold"], size=11, family="Inter"),
            xanchor="left",
        )

    title_text = (f"Top Activity Score by Day  ·  <span style=\"color:{C['gold']}\">"
                  f"{sel_label} highlighted</span>" if sel_label
                  else "Top Activity Score by Day  ·  <i>click a bar or date above to highlight</i>")

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=C["muted"], size=11), height=420,
        margin=dict(l=10, r=10, t=40, b=10),
        title=dict(text=title_text, font=dict(color=C["text"], size=12)),
        xaxis=dict(gridcolor=C["border"], range=[0, 110]),
        yaxis=dict(gridcolor=C["border"]),
    )
    return fig


def outdoor_count_fig(selected_date=None):
    labels = [pd.Timestamp(d).strftime("%b %d") for d in summary_df["date"]]
    sel_label = pd.Timestamp(selected_date).strftime("%b %d") if selected_date else None

    colors, borders, widths, opacities = [], [], [], []
    for i, (v, lbl) in enumerate(zip(summary_df["outdoor_count"], labels)):
        is_sel = (lbl == sel_label)
        base = C["green"] if v >= 5 else C["gold"] if v >= 2 else C["coral"]
        colors.append(C["gold"] if is_sel else base)
        borders.append("white" if is_sel else "rgba(0,0,0,0)")
        widths.append(2.5 if is_sel else 0)
        opacities.append(1.0 if is_sel else (0.35 if sel_label else 1.0))

    fig = go.Figure(go.Bar(
        x=labels,
        y=summary_df["outdoor_count"],
        marker=dict(color=colors, opacity=opacities,
                    line=dict(color=borders, width=widths)),
        text=summary_df["outdoor_count"],
        textposition="outside",
        textfont=dict(color="white"),
        hovertemplate="<b>%{x}</b><br>Outdoor options: %{y}<extra></extra>",
    ))

    if sel_label and sel_label in labels:
        idx = labels.index(sel_label)
        cnt = summary_df["outdoor_count"].iloc[idx]
        fig.add_annotation(
            x=sel_label, y=cnt + 0.4,
            text="★",
            showarrow=False,
            font=dict(color=C["gold"], size=16),
        )

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=C["muted"], size=11), height=260,
        margin=dict(l=10, r=10, t=30, b=10),
        title=dict(text="Number of Available Outdoor Activities per Day",
                   font=dict(color=C["text"])),
        xaxis=dict(gridcolor=C["border"]),
        yaxis=dict(gridcolor=C["border"], title="Activities"),
    )
    return fig

best_activity_table = dash_table.DataTable(
    columns=[{"name": c, "id": c} for c in ["name","category","date","score"]],
    data=best_days.assign(
        date=lambda d: d["date"].apply(lambda x: pd.Timestamp(x).strftime("%a %b %d")),
        score=lambda d: d["score"].round(1)
    ).to_dict("records"),
    style_table={"overflowX": "auto", "borderRadius": "8px"},
    style_header={"backgroundColor": C["surface"], "color": C["gold"],
                  "fontWeight": "700", "border": "1px solid " + C["border"],
                  "fontSize": "12px", "textAlign": "center"},
    style_cell={"backgroundColor": C["bg"], "color": C["text"],
                "border": "1px solid " + C["border"], "fontSize": "12px",
                "textAlign": "center", "padding": "8px 12px"},
    style_data_conditional=[
        {"if": {"row_index": "odd"}, "backgroundColor": C["card"]},
        {"if": {"filter_query": "{score} >= 75"}, "color": C["green"], "fontWeight": "600"},
        {"if": {"filter_query": "{score} >= 50 && {score} < 75"}, "color": C["gold"]},
    ],
    sort_action="native",
)

# ── App & layout ──────────────────────────────────────────────────────────────
app = Dash("NO_Recommender",
           external_stylesheets=[
               dbc.themes.CYBORG,
               "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Inter:wght@400;500;600&display=swap",
           ],
           suppress_callback_exceptions=True)

TAB_STYLE = {
    "backgroundColor": C["surface"], "color": C["muted"],
    "border": "none", "padding": "10px 20px",
    "fontFamily": "Inter, sans-serif", "fontSize": "13px", "fontWeight": "600",
}
TAB_SELECTED = {**TAB_STYLE, "backgroundColor": C["card"], "color": C["gold"],
                "borderBottom": "3px solid " + C["gold"],
                "boxShadow": "0 2px 8px rgba(0,0,0,0.08)"}

import base64 as _b64
_SVG_STR = """<svg viewBox="0 0 100 120" xmlns="http://www.w3.org/2000/svg">
  <path d="M50 10 C44 28 36 38 36 52 C36 64 42 72 50 76 C58 72 64 64 64 52 C64 38 56 28 50 10Z" fill="#d4a017"/>
  <path d="M50 18 C46 32 41 40 41 52 C41 61 45 68 50 72 C55 68 59 61 59 52 C59 40 54 32 50 18Z" fill="#b8860b" opacity="0.45"/>
  <path d="M50 55 C42 50 28 50 18 44 C14 52 18 62 26 64 C34 66 44 62 50 55Z" fill="#d4a017"/>
  <path d="M50 55 C43 52 31 52 22 47 C19 53 22 60 29 62 C37 64 45 61 50 55Z" fill="#b8860b" opacity="0.4"/>
  <path d="M50 55 C58 50 72 50 82 44 C86 52 82 62 74 64 C66 66 56 62 50 55Z" fill="#d4a017"/>
  <path d="M50 55 C57 52 69 52 78 47 C81 53 78 60 71 62 C63 64 55 61 50 55Z" fill="#b8860b" opacity="0.4"/>
  <rect x="38" y="70" width="24" height="7" rx="2" fill="#d4a017"/>
  <path d="M38 73 C30 68 20 70 15 78 C20 86 32 85 38 80Z" fill="#d4a017"/>
  <path d="M62 73 C70 68 80 70 85 78 C80 86 68 85 62 80Z" fill="#d4a017"/>
  <path d="M44 77 C44 90 46 100 50 108 C54 100 56 90 56 77Z" fill="#d4a017"/>
  <path d="M47 80 C47 90 48 98 50 105 C52 98 53 90 53 80Z" fill="#b8860b" opacity="0.35"/>
</svg>"""
_SVG_B64 = _b64.b64encode(_SVG_STR.encode()).decode()
FLEUR_SVG = html.Img(
    src="data:image/svg+xml;base64," + _SVG_B64,
    style={"width": "72px", "height": "86px", "opacity": "0.92", "flexShrink": "0"},
)

header = html.Div([
    html.Div("⚜️", style={"fontSize": "36px", "marginBottom": "8px"}),
    html.H1("New Orleans Activity Recommender",
            style={"fontFamily": "Playfair Display, serif", "color": C["gold"],
                   "fontSize": "28px", "margin": "0 0 6px 0"}),
    html.Div("Plan your perfect New Orleans day — powered by real weather forecasts",
             style={"color": C["muted"], "fontSize": "13px"}),
], style={**CARD,
          "borderLeft": "4px solid " + C["gold"],
          "marginBottom": "14px",
          "textAlign": "center",
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "center",
          "padding": "24px 20px"})

date_strip_div = html.Div([
    html.Div("SELECT A DAY", style={"color": C["muted"], "fontSize": "11px",
                                     "letterSpacing": "1px", "marginBottom": "10px"}),
    html.Div([date_btn(d, i == 0) for i, d in enumerate(DATES)],
             id="date-strip",
             style={"display": "flex", "gap": "6px", "overflowX": "auto",
                    "paddingBottom": "6px", "flexWrap": "nowrap",
                    "justifyContent": "center"}),
], style=CARD)

category_filter = dcc.Dropdown(
    id="cat-filter",
    options=[{"label": "All Categories", "value": "All"}] +
            [{"label": c, "value": c} for c in activity_df["category"].unique()],
    value="All", clearable=False,
    style={"background": C["surface"], "color": C["text"],
           "border": "1px solid " + C["border"], "borderRadius": "8px", "fontSize": "13px"},
)

tab1 = dcc.Tab(label="🎯  Recommender", style=TAB_STYLE, selected_style=TAB_SELECTED, children=[
    html.Div([
        # Overview chart
        html.Div([
            html.Div("16-DAY OVERVIEW", style={"color": C["muted"], "fontSize": "11px",
                                                "letterSpacing": "1px", "marginBottom": "8px"}),
            dcc.Graph(id="overview-chart", config={"displayModeBar": False},
                      figure=overview_fig(DATES[0])),
        ], style=CARD),
        # Two-column
        html.Div([
            html.Div([
                html.Div("WEATHER CONDITIONS", style={"color": C["muted"], "fontSize": "11px",
                                                       "letterSpacing": "1px", "marginBottom": "12px"}),
                html.Div(id="weather-panel"),
            ], style={**CARD, "flex": "1", "minWidth": "240px"}),
            html.Div([
                html.Div([
                    html.Div("ACTIVITY RECOMMENDATIONS", style={"color": C["muted"],
                                                                 "fontSize": "11px", "letterSpacing": "1px"}),
                    html.Div(category_filter, style={"marginTop": "8px"}),
                ], style={"marginBottom": "14px"}),
                html.Div(
                    id="rec-panel",
                    style={
                        "maxHeight":   "520px",
                        "overflowY":   "auto",
                        "paddingRight": "6px",
                        "scrollbarWidth": "thin",
                        "scrollbarColor": C["gold"] + " " + C["border"],
                    }
                ),
            ], style={**CARD, "flex": "2", "minWidth": "300px"}),
        ], style={"display": "flex", "gap": "14px", "flexWrap": "wrap"}),
    ])
])

tab2 = dcc.Tab(label="📊  Climate Data", style=TAB_STYLE, selected_style=TAB_SELECTED, children=[
    html.Div([
        html.Div("16-DAY STATISTICS", style={"color": C["muted"], "fontSize": "11px",
                                              "letterSpacing": "1px", "marginBottom": "12px"}),
        stats_row,
    ], style=CARD),

    html.Div([
        # ── Table header + search controls ────────────────────────────────
        html.Div([
            html.Div("DAILY CLIMATE TABLE", style={
                "color": C["gold"], "fontSize": "12px", "fontWeight": "700",
                "letterSpacing": "1.5px", "flex": "1",
                "fontFamily": "Playfair Display, serif",
            }),
        ], style={"marginBottom": "14px"}),

        # Filter controls row
        html.Div([
            # Temp slider section
            html.Div([
                html.Div([
                    html.Span("🌡️", style={"fontSize": "16px", "marginRight": "6px"}),
                    html.Span("High Temp ≥", style={
                        "color": C["text"], "fontSize": "13px", "fontWeight": "600",
                    }),
                ], style={"display": "flex", "alignItems": "center", "marginBottom": "8px"}),
                dcc.Slider(
                    id="temp-filter-slider",
                    min=80, max=100, step=1, value=80,
                    marks={
                        80: {"label": "80°F", "style": {"color": C["green"],  "fontSize": "11px"}},
                        85: {"label": "85°F", "style": {"color": C["gold"],   "fontSize": "11px"}},
                        90: {"label": "90°F", "style": {"color": C["orange"], "fontSize": "11px"}},
                        95: {"label": "95°F", "style": {"color": C["coral"],  "fontSize": "11px"}},
                        100:{"label": "100°F","style": {"color": C["coral"],  "fontSize": "11px"}},
                    },
                    tooltip={"placement": "top", "always_visible": True},
                ),
            ], style={
                "flex": "2",
                "background": C["bg"],
                "borderRadius": "10px",
                "padding": "12px 16px",
                "border": "1px solid " + C["border"],
            }),

            # Condition search section
            html.Div([
                html.Div([
                    html.Span("🔍", style={"fontSize": "16px", "marginRight": "6px"}),
                    html.Span("Search Condition", style={
                        "color": C["text"], "fontSize": "13px", "fontWeight": "600",
                    }),
                ], style={"display": "flex", "alignItems": "center", "marginBottom": "8px"}),
                dcc.Input(
                    id="condition-search",
                    type="text",
                    placeholder="e.g. rain, clear, storm…",
                    debounce=True,
                    style={
                        "background":   C["surface"],
                        "border":       "1px solid " + "rgba(109,40,217,0.4)",
                        "borderRadius": "8px",
                        "color":        C["text"],
                        "padding":      "8px 14px",
                        "fontSize":     "13px",
                        "width":        "100%",
                        "outline":      "none",
                        "boxSizing":    "border-box",
                    },
                ),
            ], style={
                "flex": "1",
                "background": C["bg"],
                "borderRadius": "10px",
                "padding": "12px 16px",
                "border": "1px solid " + C["border"],
            }),

        ], style={"display": "flex", "gap": "12px",
                  "marginBottom": "14px", "flexWrap": "wrap"}),

        # ── Table ─────────────────────────────────────────────────────────
        html.Div(
            id="climate-table-container",
            children=[climate_table],
            style={
                "scrollbarWidth": "thin",
                "scrollbarColor": C["gold"] + " " + C["border"],
            }
        ),

        html.Div(id="table-row-count",
                 style={"color": C["muted"], "fontSize": "11px",
                        "marginTop": "10px", "textAlign": "right"}),
    ], style=CARD),
])

# ── Landmark data ────────────────────────────────────────────────────────────
LANDMARKS = [
    {"name": "Frenchmen Street",    "emoji": "🎷", "desc": "Live music hub",           "lat": 29.9530, "lon": -90.0580, "cat": "Music"},
    {"name": "St. Louis Cathedral", "emoji": "⛪", "desc": "Iconic French Quarter church","lat": 29.9576, "lon": -90.0644, "cat": "Historic"},
    {"name": "Jackson Square",      "emoji": "🎢", "desc": "Historic public square",   "lat": 29.9584, "lon": -90.0644, "cat": "Historic"},
    {"name": "Café Du Monde",       "emoji": "☕", "desc": "Beignets since 1862",      "lat": 29.9578, "lon": -90.0618, "cat": "Food"},
    {"name": "Garden District",     "emoji": "🚃", "desc": "Antebellum mansions",      "lat": 29.9326, "lon": -90.0943, "cat": "Sightseeing"},
    {"name": "WWII Museum",         "emoji": "🖼️", "desc": "America's #1 history museum","lat": 29.9454, "lon": -90.0701, "cat": "Museum"},
    {"name": "Audubon Zoo",         "emoji": "🐊", "desc": "World-class wildlife park","lat": 29.9253, "lon": -90.1354, "cat": "Nature"},
    {"name": "Preservation Hall",   "emoji": "🎭", "desc": "Jazz institution since 1961","lat": 29.9576, "lon": -90.0645, "cat": "Music"},
]

LANDMARK_CAT_COLOR = {
    "Music":      "#e8b84b",
    "Historic":   "#a78bfa",
    "Food":       "#f87171",
    "Sightseeing":"#2dd4bf",
    "Museum":     "#7dd3fc",
    "Nature":     "#4ade80",
}

def landmarks_fig(selected_idx=None):
    center_lat = LANDMARKS[selected_idx]["lat"] if selected_idx is not None else 29.9511
    center_lon = LANDMARKS[selected_idx]["lon"] if selected_idx is not None else -90.0715
    zoom = 14.5 if selected_idx is not None else 12

    fig = go.Figure()

    for i, p in enumerate(LANDMARKS):
        is_sel = (selected_idx is None or i == selected_idx)
        size   = 20 if is_sel else 12
        opac   = 1.0 if is_sel else 0.3
        color  = LANDMARK_CAT_COLOR.get(p["cat"], "#fff")

        # Outer glow ring for selected
        if selected_idx is not None and i == selected_idx:
            fig.add_trace(go.Scattermapbox(
                lat=[p["lat"]], lon=[p["lon"]],
                mode="markers",
                marker=dict(size=38, color=C["gold"], opacity=0.25),
                hoverinfo="skip", showlegend=False,
            ))

        fig.add_trace(go.Scattermapbox(
            lat=[p["lat"]], lon=[p["lon"]],
            mode="markers+text",
            marker=dict(size=size, color=color, opacity=opac),
            text=[p["emoji"] + "  " + p["name"]],
            textposition="top right",
            textfont=dict(
                size=13 if is_sel else 10,
                color=C["gold"] if (selected_idx is not None and i == selected_idx) else "white",
            ),
            hovertemplate=(
                f"<b>{p['emoji']} {p['name']}</b><br>"
                f"{p['desc']}<extra></extra>"
            ),
            showlegend=False,
        ))

    fig.update_layout(
        mapbox=dict(
            style="carto-darkmatter",
            center=dict(lat=center_lat, lon=center_lon),
            zoom=zoom,
        ),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=0, r=0, t=0, b=0),
        height=480,
        showlegend=False,
        hoverlabel=dict(
            bgcolor=C["card"], font_color=C["text"],
            bordercolor=C["gold"], font_size=13,
        ),
    )
    return fig


tab3 = dcc.Tab(label="📈  Charts", style=TAB_STYLE, selected_style=TAB_SELECTED, children=[
    html.Div([
        html.Div([
            html.Div(dcc.Graph(figure=temp_range_fig(), config={"displayModeBar": False}),
                     style={**CARD, "flex": "1"}),
            html.Div(dcc.Graph(figure=precip_fig(), config={"displayModeBar": False}),
                     style={**CARD, "flex": "1"}),
        ], style={"display": "flex", "gap": "14px", "flexWrap": "wrap"}),
        html.Div([
            html.Div(dcc.Graph(figure=heat_index_fig(), config={"displayModeBar": False}),
                     style={**CARD, "flex": "1"}),
        ], style={"display": "flex", "gap": "14px"}),

        # ── New Orleans Landmarks Map — bottom of Charts tab ─────────────
        html.Div([
            # Section header
            html.Div([
                html.Div([
                    html.Span("📍", style={"fontSize": "22px", "marginRight": "10px"}),
                    html.Div([
                        html.Div("NEW ORLEANS FAMOUS LANDMARKS",
                                 style={"color": C["gold"], "fontSize": "13px",
                                        "fontWeight": "700", "letterSpacing": "1.5px",
                                        "fontFamily": "Playfair Display, serif"}),
                        html.Div("Click a landmark card to zoom in on the map",
                                 style={"color": C["muted"], "fontSize": "11px",
                                        "marginTop": "2px"}),
                    ]),
                ], style={"display": "flex", "alignItems": "center"}),
            ], style={"marginBottom": "16px",
                      "paddingBottom": "14px",
                      "borderBottom": "1px solid " + C["border"]}),

            # Map
            html.Iframe(
                id="landmarks-map",
                src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14113.5!2d-90.0715!3d29.9511!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1",
                style={
                    "width":        "100%",
                    "height":       "500px",
                    "border":       "none",
                    "borderRadius": "12px",
                    "marginBottom": "16px",
                    "boxShadow":    "0 4px 24px rgba(0,0,0,0.15)",
                },
            ),

            dcc.Store(id="selected-landmark", data=None),
        ], style={
            **CARD,
            "background": "linear-gradient(135deg, #f0ebe2 0%, #e8e0d4 100%)",
            "border": "1px solid " + C["border"],
            "boxShadow": "0 2px 16px rgba(0,0,0,0.06)",
        }),
    ])
])

tab4 = dcc.Tab(label="🏆  Best Days", style=TAB_STYLE, selected_style=TAB_SELECTED, children=[
    html.Div([
        html.Div([
            html.Div(dcc.Graph(
                id="best-days-chart",
                figure=best_days_fig(DATES[0]),
                config={"displayModeBar": False},
                style={"cursor": "pointer"},
            ), style={**CARD, "flex": "1"}),
            html.Div(dcc.Graph(
                id="outdoor-count-chart",
                figure=outdoor_count_fig(DATES[0]),
                config={"displayModeBar": False},
                style={"cursor": "pointer"},
            ), style={**CARD, "flex": "1"}),
        ], style={"display": "flex", "gap": "14px", "flexWrap": "wrap"}),
        # ── Click-detail panel ───────────────────────────────────────────────
        html.Div(id="best-day-detail", style={"marginBottom": "14px"}),
        html.Div([
            html.Div("BEST DAY PER ACTIVITY", style={"color": C["muted"], "fontSize": "11px",
                                                      "letterSpacing": "1px", "marginBottom": "12px"}),
            html.Div(
                best_activity_table,
                style={
                    "maxHeight":      "380px",
                    "overflowY":      "auto",
                    "scrollbarWidth": "thin",
                    "scrollbarColor": C["gold"] + " " + C["border"],
                }
            ),
        ], style=CARD),
    ])
])

app.layout = html.Div([
    header,
    date_strip_div,
    dcc.Tabs(id="tabs", value="tab-1", children=[tab1, tab2, tab3, tab4],
             style={"marginBottom": "14px"},
             colors={"border": C["border"], "primary": C["gold"], "background": C["surface"]}),
    dcc.Store(id="clicked-best-date", data=None),
    dcc.Store(id="selected-date", data=DATES[0]),
    dcc.Store(id="active-tab", data="tab-1"),
    # ── Photo modal overlay ────────────────────────────────────────────────
    html.Div(
        id="photo-modal",
        style={"display": "none"},
        children=[
            # Backdrop
            html.Div(id="modal-backdrop", n_clicks=0, style={
                "position": "fixed", "top": "0", "left": "0",
                "width": "100vw", "height": "100vh",
                "background": "rgba(5,8,20,0.85)", "zIndex": "999", "cursor": "pointer",
            }),
            # Modal box
            html.Div([
                # Close
                html.Div("✕", id="modal-close", n_clicks=0, style={
                    "position": "absolute", "top": "12px", "right": "16px",
                    "fontSize": "22px", "color": "white", "cursor": "pointer",
                    "zIndex": "1001", "fontWeight": "700",
                    "background": "rgba(0,0,0,0.5)", "borderRadius": "50%",
                    "width": "32px", "height": "32px", "lineHeight": "32px", "textAlign": "center",
                }),

                # ── Photo carousel ─────────────────────────────────────────
                html.Div([
                    # Image
                    html.Img(id="carousel-img", src="", style={
                        "width": "100%", "height": "240px",
                        "objectFit": "cover", "display": "block",
                        "transition": "opacity 0.3s ease",
                    }),
                    # Prev button
                    html.Div("❮", id="carousel-prev", n_clicks=0, style={
                        "position": "absolute", "left": "12px", "top": "50%",
                        "transform": "translateY(-50%)",
                        "fontSize": "22px", "color": "white", "cursor": "pointer",
                        "background": "rgba(0,0,0,0.5)", "borderRadius": "50%",
                        "width": "36px", "height": "36px", "lineHeight": "36px",
                        "textAlign": "center", "userSelect": "none", "zIndex": "10",
                        "transition": "background .2s",
                    }),
                    # Next button
                    html.Div("❯", id="carousel-next", n_clicks=0, style={
                        "position": "absolute", "right": "12px", "top": "50%",
                        "transform": "translateY(-50%)",
                        "fontSize": "22px", "color": "white", "cursor": "pointer",
                        "background": "rgba(0,0,0,0.5)", "borderRadius": "50%",
                        "width": "36px", "height": "36px", "lineHeight": "36px",
                        "textAlign": "center", "userSelect": "none", "zIndex": "10",
                        "transition": "background .2s",
                    }),
                    # Dot indicators
                    html.Div(id="carousel-dots", style={
                        "position": "absolute", "bottom": "10px", "left": "50%",
                        "transform": "translateX(-50%)",
                        "display": "flex", "gap": "6px", "zIndex": "10",
                    }),
                    # Hidden stores
                    dcc.Store(id="carousel-index", data=0),
                    dcc.Store(id="carousel-photos", data=[]),
                ], style={"position": "relative", "height": "240px", "overflow": "hidden",
                          "background": "#000"}),

                # ── Content ────────────────────────────────────────────────
                html.Div([
                    # Name row
                    html.Div([
                        html.Span(id="modal-emoji", style={"fontSize": "28px", "marginRight": "10px"}),
                        html.Div([
                            html.Div(id="modal-name", style={
                                "color": C["gold"], "fontSize": "20px", "fontWeight": "700",
                                "fontFamily": "Playfair Display, serif",
                            }),
                            html.Div(id="modal-cat"),
                        ]),
                    ], style={"display": "flex", "alignItems": "center", "marginBottom": "12px"}),

                    # Intro text
                    html.Div(id="modal-intro", style={
                        "color": C["text"], "fontSize": "13px", "lineHeight": "1.7",
                        "marginBottom": "16px", "borderLeft": "3px solid " + C["gold"],
                        "paddingLeft": "12px",
                    }),

                    # Stats row: price | rating | score
                    html.Div([
                        html.Div([
                            html.Div("💰 Price Range", style={"color": C["muted"], "fontSize": "10px",
                                                               "letterSpacing": "0.5px", "marginBottom": "3px"}),
                            html.Div(id="modal-price", style={"color": C["green"], "fontSize": "16px",
                                                               "fontWeight": "700"}),
                        ], style={"flex": "1", "background": C["surface"], "borderRadius": "10px",
                                  "padding": "10px 14px"}),
                        html.Div([
                            html.Div("⭐ Google Rating", style={"color": C["muted"], "fontSize": "10px",
                                                                  "letterSpacing": "0.5px", "marginBottom": "3px"}),
                            html.Div(id="modal-rating", style={"color": C["gold"], "fontSize": "16px",
                                                                "fontWeight": "700"}),
                        ], style={"flex": "1", "background": C["surface"], "borderRadius": "10px",
                                  "padding": "10px 14px"}),
                        html.Div([
                            html.Div("🎯 Comfort Score", style={"color": C["muted"], "fontSize": "10px",
                                                                  "letterSpacing": "0.5px", "marginBottom": "3px"}),
                            html.Div(id="modal-score", style={"fontSize": "16px", "fontWeight": "700"}),
                        ], style={"flex": "1", "background": C["surface"], "borderRadius": "10px",
                                  "padding": "10px 14px"}),
                    ], style={"display": "flex", "gap": "8px"}),

                ], style={"padding": "16px 20px 20px"}),
            ], style={
                "position": "fixed",
                "top": "50%", "left": "50%",
                "transform": "translate(-50%, -50%)",
                "width": "min(560px, 92vw)",
                "background": C["card"],
                "borderRadius": "14px",
                "border": "1px solid " + C["border"],
                "zIndex": "1000",
                "boxShadow": "0 24px 80px rgba(0,0,0,0.7)",
                "overflow": "hidden",
                "maxHeight": "90vh",
                "overflowY": "auto",
            }),
        ],
    ),
], style={
    "background": "linear-gradient(160deg, #f5f3ef 0%, #ede8df 50%, #f0ebe2 100%)",
    "minHeight":  "100vh",
    "padding":    "24px",
    "fontFamily": "Inter, sans-serif",
    "maxWidth":   "1200px",
    "margin":     "0 auto",
})

# ── Callbacks ─────────────────────────────────────────────────────────────────
@app.callback(
    Output("selected-date", "data"),
    Output("date-strip", "children"),
    Input({"type": "date-btn", "index": ALL}, "n_clicks"),
    State("selected-date", "data"),
    prevent_initial_call=True,
)
def pick_date(clicks, current):
    triggered = ctx.triggered_id
    selected = current
    if triggered and isinstance(triggered, dict) and triggered.get("type") == "date-btn":
        selected = triggered["index"]
    new_strip = [date_btn(d, d == selected) for d in DATES]
    return selected, new_strip

@app.callback(
    Output("weather-panel", "children"),
    Output("overview-chart", "figure"),
    Input("selected-date", "data"),
)
def update_weather(date_str):
    return weather_card(date_str), overview_fig(date_str)

@app.callback(
    Output("rec-panel", "children"),
    Input("selected-date", "data"),
    Input("cat-filter", "value"),
)
def update_recs(date_str, category):
    row = clean_df.loc[date_str]
    recs = score_activities(row)
    if category != "All":
        recs = recs[recs["category"] == category]
    if recs.empty:
        return html.Div("No activities match for this day.",
                        style={"color": C["muted"], "padding": "20px", "textAlign": "center"})
    dt_label = pd.Timestamp(date_str).strftime("%A, %b %d")
    summary = html.Div(
        f"✅  {len(recs)} activities recommended for {dt_label}",
        style={"color": C["green"], "fontSize": "13px", "marginBottom": "12px", "fontWeight": "600"},
    )
    return [summary] + [rec_card(r) for _, r in recs.iterrows()]

# ── Callback: show photo modal on rec-card click ─────────────────────────────
@app.callback(
    Output("photo-modal",    "style"),
    Output("carousel-img",   "src"),
    Output("carousel-photos","data"),
    Output("carousel-index", "data"),
    Output("carousel-dots",  "children"),
    Output("modal-emoji",    "children"),
    Output("modal-name",     "children"),
    Output("modal-intro",    "children"),
    Output("modal-cat",      "children"),
    Output("modal-price",    "children"),
    Output("modal-rating",   "children"),
    Output("modal-score",    "children"),
    Output("modal-score",    "style"),
    Input({"type": "rec-card", "index": ALL}, "n_clicks"),
    Input("modal-backdrop", "n_clicks"),
    Input("modal-close",    "n_clicks"),
    State("selected-date",  "data"),
    prevent_initial_call=True,
)
def toggle_modal(card_clicks, backdrop, close_clicks, date_str):
    triggered = ctx.triggered_id
    EMPTY = {"display": "none"}, "", [], 0, [], "", "", "", "", "", "", "", {}

    if triggered in ("modal-backdrop", "modal-close"):
        return EMPTY

    if not triggered or not isinstance(triggered, dict):
        from dash.exceptions import PreventUpdate
        raise PreventUpdate

    aid = triggered.get("index")
    if not aid or not any(card_clicks):
        from dash.exceptions import PreventUpdate
        raise PreventUpdate

    act_row = activity_df[activity_df["id"] == aid]
    if act_row.empty:
        from dash.exceptions import PreventUpdate
        raise PreventUpdate
    act  = act_row.iloc[0]
    meta = ACTIVITY_META.get(aid, {})

    # Score
    row   = clean_df.loc[date_str]
    recs  = score_activities(row)
    match = recs[recs["id"] == aid]
    score = match["score"].values[0] if not match.empty else 0
    col   = score_color(score)

    cat = act["category"]
    cat_badge = html.Div(cat, style={
        "display": "inline-block", "padding": "2px 10px", "borderRadius": "20px",
        "fontSize": "11px", "fontWeight": "600", "marginTop": "3px",
        "background": CAT_COLOR.get(cat, "#555") + "33",
        "color": CAT_COLOR.get(cat, "#aaa"),
        "border": "1px solid " + CAT_COLOR.get(cat, "#555") + "55",
    })

    # Star rating display
    rating = meta.get("rating", 4.5)
    stars  = "★" * int(rating) + ("½" if rating % 1 >= 0.5 else "") + "☆" * (5 - int(rating+0.5))
    rating_txt = f"{rating} {stars}"

    photos = meta.get("photos", [ACTIVITY_PHOTOS.get(aid, "")])
    dots = [
        html.Div(style={
            "width": "8px", "height": "8px", "borderRadius": "50%",
            "background": C["gold"] if i == 0 else "rgba(255,255,255,0.4)",
            "cursor": "pointer",
        }) for i in range(len(photos))
    ]

    return (
        {"display": "block"},
        photos[0] if photos else "",
        photos,
        0,
        dots,
        act["emoji"],
        act["name"],
        meta.get("intro", act["description"]),
        cat_badge,
        meta.get("price", "—"),
        rating_txt,
        str(int(score)),
        {"color": col, "fontSize": "18px", "fontWeight": "700",
         "fontFamily": "Playfair Display, serif"},
    )


# ── Callback: carousel prev/next ─────────────────────────────────────────────
@app.callback(
    Output("carousel-img",   "src",  allow_duplicate=True),
    Output("carousel-index", "data", allow_duplicate=True),
    Output("carousel-dots",  "children", allow_duplicate=True),
    Input("carousel-prev",   "n_clicks"),
    Input("carousel-next",   "n_clicks"),
    State("carousel-photos", "data"),
    State("carousel-index",  "data"),
    prevent_initial_call=True,
)
def navigate_carousel(prev_clicks, next_clicks, photos, current_idx):
    if not photos:
        from dash.exceptions import PreventUpdate
        raise PreventUpdate

    triggered = ctx.triggered_id
    n = len(photos)
    if triggered == "carousel-prev":
        new_idx = (current_idx - 1) % n
    else:
        new_idx = (current_idx + 1) % n

    dots = [
        html.Div(style={
            "width": "8px", "height": "8px", "borderRadius": "50%",
            "background": C["gold"] if i == new_idx else "rgba(255,255,255,0.4)",
            "cursor": "pointer", "transition": "background .2s",
        }) for i in range(n)
    ]
    return photos[new_idx], new_idx, dots


# ── Callback: landmark card click → update Google Maps embed src ─────────────
@app.callback(
    Output("landmarks-map",     "src"),
    Output("selected-landmark", "data"),
    Input({"type": "landmark-btn", "index": ALL}, "n_clicks"),
    State("selected-landmark",  "data"),
    prevent_initial_call=True,
)
def highlight_landmark(clicks, current):
    triggered = ctx.triggered_id
    if not triggered or not isinstance(triggered, dict):
        from dash.exceptions import PreventUpdate
        raise PreventUpdate
    idx = triggered.get("index")
    if idx is None:
        from dash.exceptions import PreventUpdate
        raise PreventUpdate
    new_idx = None if idx == current else idx

    if new_idx is None:
        # Full overview
        src = "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14113.5!2d-90.0715!3d29.9511!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1"
    else:
        p = LANDMARKS[new_idx]
        # Build Google Maps embed centered on selected landmark
        lat, lon = p["lat"], p["lon"]
        place = p["name"].replace(" ", "+")
        src = (
            f"https://www.google.com/maps/embed/v1/place"
            f"?key=AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY"
            f"&q={place}+New+Orleans+LA"
            f"&zoom=16"
        )
    return src, new_idx


# ── Callback: climate table filter (temp slider + condition search) ──────────
@app.callback(
    Output("climate-table-container", "children"),
    Output("table-row-count", "children"),
    Input("temp-filter-slider", "value"),
    Input("condition-search", "value"),
)
def filter_climate_table(min_temp, condition_kw):
    df = table_df[table_cols].copy()

    # Filter by high temp threshold
    if min_temp and min_temp > 80:
        df = df[df["High °F"] >= min_temp]

    # Filter by condition keyword
    if condition_kw and condition_kw.strip():
        kw = condition_kw.strip().lower()
        df = df[df["Condition"].str.lower().str.contains(kw, na=False)]

    count = len(df)
    label = f"Showing {count} of {len(table_df)} days"
    if count == 0:
        return html.Div(
            "No days match your filters.",
            style={"color": C["muted"], "padding": "24px", "textAlign": "center"},
        ), label

    filtered_table = dash_table.DataTable(
        columns=[{"name": c, "id": c} for c in table_cols],
        data=df.to_dict("records"),
        style_table={
            "overflowX": "auto", "overflowY": "auto",
            "maxHeight": "420px", "borderRadius": "8px", "minWidth": "100%",
        },
        fixed_rows={"headers": True},
        style_header={
            "backgroundColor": C["surface"], "color": C["gold"],
            "fontWeight": "700", "border": "1px solid " + C["border"],
            "fontSize": "12px", "textAlign": "center",
        },
        style_cell={
            "backgroundColor": C["bg"], "color": C["text"],
            "border": "1px solid " + C["border"], "fontSize": "12px",
            "textAlign": "center", "padding": "8px 12px",
            "fontFamily": "Inter, sans-serif", "minWidth": "80px",
        },
        style_data_conditional=[
            {"if": {"row_index": "odd"}, "backgroundColor": C["card"]},
            {"if": {"filter_query": "{Precip in} > 0.2"},
             "color": C["sky"], "fontWeight": "600"},
            {"if": {"filter_query": "{High °F} > 90"},
             "color": C["coral"], "fontWeight": "600"},
        ],
        sort_action="native",
        filter_action="native",
        page_action="none",
    )
    return filtered_table, label


# ── Callback: sync Best Days charts when date changes ────────────────────────
@app.callback(
    Output("best-days-chart", "figure"),
    Output("outdoor-count-chart", "figure"),
    Input("selected-date", "data"),
)
def sync_best_charts(date_str):
    return best_days_fig(date_str), outdoor_count_fig(date_str)


# ── Callback: click bar → store date + switch tab ────────────────────────────
@app.callback(
    Output("selected-date", "data", allow_duplicate=True),
    Output("date-strip", "children", allow_duplicate=True),
    Output("tabs", "value"),
    Output("clicked-best-date", "data"),
    Input("best-days-chart", "clickData"),
    Input("outdoor-count-chart", "clickData"),
    State("selected-date", "data"),
    prevent_initial_call=True,
)
def chart_click_to_tab(click_best, click_outdoor, current):
    # Determine which chart was clicked
    click = click_best or click_outdoor
    if not click:
        from dash.exceptions import PreventUpdate
        raise PreventUpdate

    # Extract date from the y-axis label (best-days) or x-axis (outdoor-count)
    point = click["points"][0]
    label = point.get("y") or point.get("x") or ""   # "Mon Jun 08" or "Jun 08"

    # Match label back to a DATES entry
    selected = current
    for d in DATES:
        ts = pd.Timestamp(d)
        if ts.strftime("%a %b %d") == label or ts.strftime("%b %d") == label:
            selected = d
            break

    new_strip = [date_btn(d, d == selected) for d in DATES]
    # Switch to Recommender tab and store the clicked date for detail panel
    return selected, new_strip, "tab-1", selected


# ── Callback: render detail panel in Best Days tab ────────────────────────────
@app.callback(
    Output("best-day-detail", "children"),
    Input("clicked-best-date", "data"),
)
def render_best_day_detail(date_str):
    if not date_str:
        return html.Div(
            "👆 Click any bar above to see that day\'s weather and recommendations here.",
            style={"color": C["muted"], "textAlign": "center",
                   "padding": "20px", "fontSize": "13px"},
        )
    row  = clean_df.loc[date_str]
    recs = score_activities(row)
    dt   = pd.Timestamp(date_str).strftime("%A, %B %d")

    return html.Div([
        # Header row
        html.Div([
            html.Div([
                html.Span(row["weather_icon"], style={"fontSize": "32px", "marginRight": "10px"}),
                html.Div([
                    html.Div(f"{dt} — {row['weather_desc']}",
                             style={"color": C["gold"], "fontWeight": "700",
                                    "fontFamily": "Playfair Display, serif", "fontSize": "18px"}),
                    html.Div("Click a bar to explore · now showing details below",
                             style={"color": C["muted"], "fontSize": "11px"}),
                ]),
            ], style={"display": "flex", "alignItems": "center", "flex": "1"}),
        ], style={"marginBottom": "14px"}),

        # Weather stats strip
        html.Div([
            _stat("High",      str(int(row["temp_max_f"])) + " °F",          C["coral"]),
            _stat("Low",       str(int(row["temp_min_f"])) + " °F",          C["sky"]),
            _stat("Rain",      str(round(float(row["precip_in"]), 2)) + " in", C["teal"]),
            _stat("Rain Prob", str(int(row["precip_prob_pct"])) + " %",      C["sky"]),
            _stat("Wind",      str(int(row["wind_max_mph"])) + " mph",       C["gold"]),
            _stat("Cloud",     str(int(row["cloud_pct"])) + " %",            C["muted"]),
        ], style={"display": "grid", "gridTemplateColumns": "repeat(6, 1fr)",
                  "gap": "10px", "marginBottom": "14px"}),

        # Recommended activities
        html.Div(
            f"🎯 {len(recs)} activities recommended for this day",
            style={"color": C["green"], "fontWeight": "600",
                   "fontSize": "13px", "marginBottom": "10px"},
        ),
        html.Div(
            [rec_card(r) for _, r in recs.iterrows()],
            style={"display": "grid",
                   "gridTemplateColumns": "repeat(auto-fill, minmax(320px, 1fr))",
                   "gap": "10px"},
        ),
    ], style={**CARD, "borderLeft": "3px solid " + C["gold"]})


# ── Launch ────────────────────────────────────────────────────────────────────
app.run(jupyter_mode="external", debug=False, port=8052)