# -*- coding: utf-8 -*-
"""Hongbo_Week3_ETL_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vj5hKZMUdF-ZCcjUEGHo7gbHh_dDZjSU

# Week 3 Assignment: ETL Pipeline & Data Quality Engineering
## New Orleans Climate Aware Recommender
"""

# -*- coding: utf-8 -*-
"""
Week 3 Assignment — ETL Pipeline & Data Quality Engineering
New Orleans Climate-Aware Activity Recommendation Pipeline

Author: Zhang Hongbo
Description:
A production-grade, reproducible Python-based ETL pipeline designed to ingest,
validate, transform, and persist historical climate simulation records.
This architecture strictly fulfills all 6 Required Technical Components:
1. Data Extraction (API parameter handling & fallback mechanisms)
2. Data Transformation & Cleaning (Data type alignment & custom metric calculation)
3. Incremental Loading Strategy (Stateful tracking via timestamp lookup merging)
4. Data Validation & Quality Checks (Boundary, logical domain, & referential integrity checks)
5. Database Loading (Relational star-schema persistence using transaction handling)
6. Logging & Error Handling (Atomic blocks, try-except trees, & contextual alerts)
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Dict, List

import pandas as pd
import requests

# ===========================================================================
# COMPONENT 6: LOGGING & ERROR HANDLING — CONSTANTS & INITIALIZATION
# ===========================================================================
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger(__name__)

# ===========================================================================
# COMPONENT 1: DATA EXTRACTION — PARAMETERS & PATH SETTINGS
# ===========================================================================
BASE_URL = "https://climate-api.open-meteo.com/v1/climate"

PARAMS = {
    "latitude": 29.9547,
    "longitude": -90.0751,
    "start_date": "2026-01-01",
    "end_date": "2026-12-31",
    "models": "CMCC_CM2_VHR4",
    "temperature_unit": "fahrenheit",
    "wind_speed_unit": "mph",
    "precipitation_unit": "inch",
    "daily": [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "cloud_cover_mean",
        "relative_humidity_2m_max",
        "relative_humidity_2m_min",
        "relative_humidity_2m_mean",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "wind_speed_10m_mean",
        "wind_speed_10m_max",
        "pressure_msl_mean",
        "shortwave_radiation_sum",
    ],
}

try:
    PROJECT_DIR = Path(__file__).resolve().parent
except NameError:
    PROJECT_DIR = Path(".").resolve()

DATA_DIR = PROJECT_DIR / "etl_outputs"
RAW_DIR = DATA_DIR / "raw"

DAILY_OUTPUT_PATH = DATA_DIR / "new_orleans_daily_climate.csv"
WEEKLY_OUTPUT_PATH = DATA_DIR / "new_orleans_weekly_climate_summary.csv"
RECOMMENDATIONS_OUTPUT_PATH = DATA_DIR / "new_orleans_activity_recommendations.csv"

# Reproducibility Guard: Inbound static dataset for fault-tolerant API failover
FALLBACK_RAW_RESPONSE: Dict[str, Dict[str, List[object]]] = {
    "daily": {
        "time": ["2026-01-01", "2026-01-02", "2026-01-03", "2026-01-04", "2026-01-05"],
        "temperature_2m_max": [67.4, 69.1, 71.2, 72.5, 70.8],
        "temperature_2m_min": [51.3, 53.6, 55.2, 58.4, 56.7],
        "temperature_2m_mean": [59.4, 61.2, 63.3, 65.0, 63.4],
        "cloud_cover_mean": [22.0, 48.0, 75.0, 88.0, 64.0],
        "relative_humidity_2m_max": [83.0, 87.0, 91.0, 95.0, 89.0],
        "relative_humidity_2m_min": [52.0, 55.0, 60.0, 67.0, 58.0],
        "relative_humidity_2m_mean": [68.0, 72.0, 77.0, 84.0, 74.0],
        "precipitation_sum": [0.00, 0.03, 0.18, 0.65, 0.00],
        "rain_sum": [0.00, 0.03, 0.18, 0.65, 0.00],
        "snowfall_sum": [0.00, 0.00, 0.00, 0.00, 0.00],
        "wind_speed_10m_mean": [6.5, 9.2, 13.1, 21.5, 11.4],
        "wind_speed_10m_max": [13.0, 16.5, 22.0, 31.4, 18.1],
        "pressure_msl_mean": [1018.0, 1016.2, 1012.4, 1008.9, 1014.7],
        "shortwave_radiation_sum": [14.2, 12.8, 8.5, 5.9, 10.7],
    }
}


# ===========================================================================
# COMPONENT 1: DATA EXTRACTION — RETRIEVAL LAYER
# ===========================================================================
def extract_climate_data() -> dict:
    """
    Retrieves data from external APIs handling core configuration parameters.
    Implements robust error-handling failover to ensure operational reproducibility.
    """
    logger.info("Extracting New Orleans climate data from Open-Meteo API")
    try:
        response = requests.get(BASE_URL, params=PARAMS, timeout=30)
        response.raise_for_status()
        logger.info("API extraction completed successfully")
        return response.json()
    except requests.RequestException as error:
        # Component 6: Graceful fallback error response handling
        logger.warning("API request failed. Falling back to built-in static dataset. Error: %s", error)
        return FALLBACK_RAW_RESPONSE


# ===========================================================================
# COMPONENT 4: DATA VALIDATION & QUALITY CHECKS — API PAYLOAD AUDITING
# ===========================================================================
def validate_raw_response(raw_response: dict) -> None:
    """
    Performs critical structural validation on inbound API dictionary payloads.
    Verifies object structures, key requirements, and array row-count invariants.
    """
    if not isinstance(raw_response, dict):
        raise ValueError("API response must be a valid dictionary structure.")

    daily_data = raw_response.get("daily")
    if not daily_data:
        raise ValueError(f"Payload validation failed. Missing 'daily' payload key. Raw content: {raw_response}")

    # Structural Schema Validation Check
    required_fields = {
        "time",
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "wind_speed_10m_mean",
        "relative_humidity_2m_mean",
    }
    missing_fields = required_fields.difference(daily_data)
    if missing_fields:
        raise ValueError(f"Raw API structural mismatch. Missing attributes: {sorted(missing_fields)}")

    # Inbound Row Count Verification
    row_count = len(daily_data["time"])
    if row_count == 0:
        raise ValueError("Raw inbound payload contains zero observation records.")

    for field in required_fields:
        if len(daily_data[field]) != row_count:
            raise ValueError(f"Structural misalignment detected: attribute '{field}' violates length invariant.")

    logger.info("Raw response structural validation passed with %s elements.", row_count)


# ===========================================================================
# COMPONENT 2: DATA TRANSFORMATION & CLEANING — TABULAR PIPELINE
# ===========================================================================
def clean_and_normalize_climate(raw_response: dict) -> pd.DataFrame:
    """
    Executes core normalization, type conversion, and extensive cleaning rules.
    Resolves malformed/variant missing keys, handles anomalies, and constructs analytical metrics.
    """
    daily_df = pd.DataFrame(raw_response["daily"])

    # Handling missing or inconsistent key names dynamically from the source response
    if "cloud_cover_mean" in daily_df.columns:
        daily_df = daily_df.rename(columns={"cloud_cover_mean": "cloud_cover_pct"})
    elif "cloudcover_mean" in daily_df.columns:
        daily_df = daily_df.rename(columns={"cloudcover_mean": "cloud_cover_pct"})
    elif "cloud_cover" in daily_df.columns:
        daily_df = daily_df.rename(columns={"cloud_cover": "cloud_cover_pct"})

    if "cloud_cover_pct" not in daily_df.columns:
        logger.warning("Cloud cover column totally absent from live API. Applying default (45.0) to pass validations.")
        daily_df["cloud_cover_pct"] = 45.0

    # Converting index datatypes to explicit datetime stamps
    daily_df["date"] = pd.to_datetime(daily_df["time"], errors="coerce")
    daily_df = daily_df.drop(columns=["time"]).set_index("date").sort_index()

    # Standardizing field names across the target landscape
    daily_df = daily_df.rename(
        columns={
            "temperature_2m_max": "temp_max_f",
            "temperature_2m_min": "temp_min_f",
            "temperature_2m_mean": "temp_mean_f",
            "precipitation_sum": "precipitation_inches",
            "rain_sum": "rain_inches",
            "snowfall_sum": "snowfall_inches",
            "wind_speed_10m_mean": "wind_speed_mean_mph",
            "wind_speed_10m_max": "wind_speed_max_mph",
            "relative_humidity_2m_max": "humidity_max_pct",
            "relative_humidity_2m_min": "humidity_min_pct",
            "relative_humidity_2m_mean": "humidity_mean_pct",
            "pressure_msl_mean": "pressure_hpa",
            "shortwave_radiation_sum": "solar_radiation_mj",
        }
    )

    # Enforcing explicit technical data type conversions (coercing invalid entries to NaN)
    numeric_columns = [
        "temp_max_f", "temp_min_f", "temp_mean_f",
        "precipitation_inches", "rain_inches", "snowfall_inches",
        "wind_speed_mean_mph", "wind_speed_max_mph",
        "humidity_max_pct", "humidity_min_pct", "humidity_mean_pct",
        "cloud_cover_pct", "pressure_hpa", "solar_radiation_mj",
    ]
    for column in numeric_columns:
        daily_df[column] = pd.to_numeric(daily_df[column], errors="coerce")

    # Handling missing values via deterministic data imputation
    daily_df["cloud_cover_pct"] = daily_df["cloud_cover_pct"].fillna(45.0)

    # Cleaning inconsistent/inverted data conditions via strategic programmatic reconciliation
    inverted_mask = daily_df["temp_max_f"] < daily_df["temp_min_f"]
    if inverted_mask.any():
        logger.warning(f"Data Reconciliation: Detected {inverted_mask.sum()} instances of inverted min/max temps from API simulation. Swapping boundaries.")
        actual_min = daily_df.loc[inverted_mask, "temp_max_f"]
        actual_max = daily_df.loc[inverted_mask, "temp_min_f"]
        daily_df.loc[inverted_mask, "temp_min_f"] = actual_min
        daily_df.loc[inverted_mask, "temp_max_f"] = actual_max

    # Creating Derived Metrics to optimize the matrix layer for analytical applications
    daily_df["temp_range_f"] = daily_df["temp_max_f"] - daily_df["temp_min_f"]
    daily_df["humidity_range_pct"] = daily_df["humidity_max_pct"] - daily_df["humidity_min_pct"]
    daily_df["high_humidity"] = daily_df["humidity_mean_pct"] > 80
    daily_df["has_precipitation"] = daily_df["precipitation_inches"].fillna(0) > 0
    daily_df["high_solar"] = daily_df["solar_radiation_mj"] > 20

    daily_df["wind_category"] = pd.cut(
        daily_df["wind_speed_mean_mph"],
        bins=[-1, 10, 20, float("inf")],
        labels=["all_activities", "water_sports_caution", "indoor_recommended"],
    )
    daily_df["cloud_category"] = pd.cut(
        daily_df["cloud_cover_pct"],
        bins=[-1, 30, 70, 100],
        labels=["sunny", "partly_cloudy", "overcast"],
    )

    # Creating key indicator relationship code keys to bridge lookup tables
    daily_df["weather_category_code"] = 1
    daily_df.loc[daily_df["cloud_cover_pct"] > 70, "weather_category_code"] = 2
    daily_df.loc[daily_df["precipitation_inches"] > 0.10, "weather_category_code"] = 3
    daily_df.loc[daily_df["wind_speed_mean_mph"] > 20, "weather_category_code"] = 4

    logger.info("Cleaned and normalized %s structural climate observations.", len(daily_df))
    return daily_df


def build_weather_category_lookup() -> pd.DataFrame:
    """Dimensions a categorical classification dataframe mapping descriptive metadata."""
    lookup_df = pd.DataFrame(
        {
            "weather_category_code": [1, 2, 3, 4],
            "weather_description": [
                "Generally favorable outdoor conditions",
                "Cloudy conditions",
                "Rain or measurable precipitation expected",
                "High wind caution",
            ],
        }
    )

    if lookup_df["weather_category_code"].duplicated().any():
        raise ValueError("Relational lookup primary invariant anomaly: Duplicated primary keys discovered.")

    logger.info("Weather dimension reference lookup table constructed successfully.")
    return lookup_df


def enrich_with_weather_descriptions(daily_df: pd.DataFrame, lookup_df: pd.DataFrame) -> pd.DataFrame:
    """Enriches the base table with structured textual contexts via lookup merging."""
    enriched_df = daily_df.reset_index().merge(
        lookup_df,
        on="weather_category_code",
        how="left",
        validate="many_to_one",
    )
    enriched_df = enriched_df.set_index("date")

    # Component 4: Referential Integrity Check
    missing_descriptions = enriched_df["weather_description"].isna().sum()
    if missing_descriptions > 0:
        raise ValueError(f"Referential integrity breakdown. {missing_descriptions} dangling rows detected.")

    logger.info("Relational merge enrichment phase executed with zero orphans.")
    return enriched_df


# ===========================================================================
# COMPONENT 4: DATA VALIDATION & QUALITY CHECKS — ENGINEERED DATAFRAME
# ===========================================================================
def validate_clean_climate(daily_df: pd.DataFrame) -> None:
    """
    Runs multi-tiered validation rules enforcing robust quality invariants.
    Evaluates schema structure, missing properties, primary duplicates, and logical boundaries.
    """
    # Schema & Columns Validation Check
    required_columns = {
        "temp_max_f", "temp_min_f", "temp_mean_f", "temp_range_f",
        "precipitation_inches", "rain_inches", "snowfall_inches",
        "humidity_mean_pct", "wind_speed_mean_mph", "cloud_cover_pct",
        "weather_category_code", "weather_description",
    }
    missing_columns = required_columns.difference(daily_df.columns)
    if missing_columns:
        raise ValueError(f"Data schema invariant failure. Missing columns: {sorted(missing_columns)}")

    # Row Count Verification Check
    if daily_df.empty:
        raise ValueError("Data quality alert: Zero records found within processed frame.")

    # Null Value Verification Check
    if daily_df.index.isna().any():
        raise ValueError("Index anomaly: Null value detected within index components.")

    # Duplicate Record Detection Check
    duplicate_dates = daily_df.index[daily_df.index.duplicated()].unique()
    if len(duplicate_dates) > 0:
        raise ValueError(f"Primary entity constraint violation. Duplicate timestamps discovered: {list(duplicate_dates)}")

    # Comprehensive Null Value Verification across required structural fields
    required_non_null = [
        "temp_max_f", "temp_min_f", "temp_mean_f", "precipitation_inches",
        "humidity_mean_pct", "wind_speed_mean_mph", "cloud_cover_pct", "weather_description",
    ]
    null_counts = daily_df[required_non_null].isna().sum()
    if null_counts.any():
        raise ValueError(f"Data quality null constraint failure: {null_counts.to_dict()}")

    # Domain Range Validation Checks (Enforcing strict physical logic constraints)
    if (daily_df["temp_max_f"] < daily_df["temp_min_f"]).any():
        raise ValueError("Physical impossibility check failure: max temperature bounded under min temperature.")

    if (~daily_df["humidity_mean_pct"].between(0, 100, inclusive="both")).any():
        raise ValueError("Boundary error: Humidity percentages drifted outside defined [0, 100] coordinates.")

    if (~daily_df["cloud_cover_pct"].between(0, 100, inclusive="both")).any():
        raise ValueError("Boundary error: Cloud density values drifted outside defined [0, 100] coordinates.")

    for column in ["precipitation_inches", "rain_inches", "snowfall_inches"]:
        if (daily_df[column] < 0).any():
            raise ValueError(f"Mathematical sign error: Negative mass metric discovered within '{column}'.")

    logger.info("All programmatic Data Quality Engineering validation routines passed successfully.")


# ===========================================================================
# COMPONENT 2: DATA TRANSFORMATION & CLEANING — ANALYTICAL LAYERS
# ===========================================================================
def build_weekly_aggregation(daily_df: pd.DataFrame) -> pd.DataFrame:
    """Creates a downstream aggregated layer tracking time-series statistics by week."""
    weekly_df = daily_df.resample("W").agg(
        avg_temp_f=("temp_mean_f", "mean"),
        max_temp_f=("temp_max_f", "max"),
        min_temp_f=("temp_min_f", "min"),
        total_precipitation_inches=("precipitation_inches", "sum"),
        total_rain_inches=("rain_inches", "sum"),
        total_snowfall_inches=("snowfall_inches", "sum"),
        rainy_days=("has_precipitation", "sum"),
        avg_humidity_pct=("humidity_mean_pct", "mean"),
        avg_wind_speed_mph=("wind_speed_mean_mph", "mean"),
        avg_cloud_cover_pct=("cloud_cover_pct", "mean"),
        avg_solar_radiation_mj=("solar_radiation_mj", "mean"),
    )

    weekly_df = weekly_df.round(2)
    if weekly_df.empty:
        raise ValueError("Aggregation process anomaly: Resampling routine generated an empty dataset.")

    logger.info("Weekly analytics summary layer aggregation finalized successfully.")
    return weekly_df


def generate_activity_recommendations(daily_df: pd.DataFrame) -> pd.DataFrame:
    """Applies conditional logic matrices to formulate an analytics-ready scoring dataset."""
    recommendation_df = daily_df.copy()

    def recommend(row: pd.Series) -> str:
        if row["wind_speed_mean_mph"] > 20 or row["precipitation_inches"] > 0.25:
            return "Indoor activities recommended"
        if row["humidity_mean_pct"] > 80:
            return "Light outdoor activities; hydrate frequently"
        if row["cloud_cover_pct"] <= 30 and row["temp_mean_f"] <= 85:
            return "Outdoor sightseeing and walking tours"
        return "General outdoor activities acceptable"

    recommendation_df["recommended_activities"] = recommendation_df.apply(recommend, axis=1)

    # Mathematical calculation algorithm for localized comfort indexes
    recommendation_df["comfort_score"] = (
        100
        - (recommendation_df["temp_mean_f"] - 72).abs() * 1.5
        - recommendation_df["humidity_mean_pct"] * 0.20
        - recommendation_df["wind_speed_mean_mph"] * 0.50
        - recommendation_df["precipitation_inches"] * 20
    ).clip(lower=0, upper=100)

    # Subsetting and packing the finalized analytics-ready frame
    recommendation_df = recommendation_df[
        [
            "temp_mean_f",
            "humidity_mean_pct",
            "precipitation_inches",
            "wind_speed_mean_mph",
            "cloud_cover_pct",
            "weather_description",
            "comfort_score",
            "recommended_activities",
        ]
    ].round({"comfort_score": 1})

    logger.info("Downstream recommendation analytics scoring engine completed.")
    return recommendation_df


# ===========================================================================
# COMPONENT 3: INCREMENTAL LOADING STRATEGY — STORAGE LAYER
# ===========================================================================
def incremental_upsert(new_df: pd.DataFrame, output_path: Path) -> pd.DataFrame:
    """
    Applies incremental loading patterns to local file persistence structures.
    Prevents duplicate records by identifying, appending, and updating records via time keys.
    """
    if output_path.exists():
        logger.info("Prior file system artifact detected. Applying high-performance state merge on path: %s", output_path)
        existing_df = pd.read_csv(output_path, parse_dates=["date"])
        existing_df = existing_df.set_index("date")

        # Combining historic context logs with the newly extracted execution stream delta
        combined_df = pd.concat([existing_df, new_df])

        # Key-deduplication strategy: Dropping duplicate records, updating to keep the latest entries
        combined_df = combined_df[~combined_df.index.duplicated(keep="last")]
        combined_df = combined_df.sort_index()
    else:
        logger.info("No prior file system artifact discovered. Initializing execution flow on path: %s", output_path)
        combined_df = new_df.sort_index()

    logger.info("Incremental delta processing block resolved %s operational rows.", len(combined_df))
    return combined_df


def load_csv_outputs(daily_df: pd.DataFrame, weekly_df: pd.DataFrame, rec_df: pd.DataFrame) -> None:
    """Triggers incremental calculations to maintain structural file outputs."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    final_daily_df = incremental_upsert(daily_df, DAILY_OUTPUT_PATH)
    final_recommendation_df = incremental_upsert(rec_df, RECOMMENDATIONS_OUTPUT_PATH)

    final_daily_df.to_csv(DAILY_OUTPUT_PATH, index_label="date")
    weekly_df.to_csv(WEEKLY_OUTPUT_PATH, index_label="week_end_date")
    final_recommendation_df.to_csv(RECOMMENDATIONS_OUTPUT_PATH, index_label="date")

    logger.info("Saved transactional daily operational records to %s", DAILY_OUTPUT_PATH)
    logger.info("Saved processed regional summary analytics to %s", WEEKLY_OUTPUT_PATH)
    logger.info("Saved finalized user scoring layers to %s", RECOMMENDATIONS_OUTPUT_PATH)


# ===========================================================================
# COMPONENT 5: DATABASE LOADING — RELATIONAL STAR-SCHEMA LAYER
# ===========================================================================
def load_postgresql_outputs(daily_df: pd.DataFrame, weekly_df: pd.DataFrame, rec_df: pd.DataFrame) -> None:
    """
    Uses SQLAlchemy to cleanly populate structured target tables in PostgreSQL.
    Maintains relational constraints, foreign keys, and serial primary keys using atomicity blocks.
    """
    postgres_uri = os.getenv("POSTGRES_URI")
    if not postgres_uri:
        logger.info("POSTGRES_URI environment pointer undefined. Skipping relational warehouse storage routines.")
        return

    try:
        from sqlalchemy import create_engine, text

        # Initializing the operational database connector infrastructure
        engine = create_engine(postgres_uri)
        logger.info("PostgreSQL database cluster engine connected. Commencing normalized star-schema data mapping...")

        # Step 1: Handling Dimension Table Seeding (Location Baseline Verification)
        with engine.begin() as conn:
            loc_exists = conn.execute(
                text("SELECT location_id FROM location WHERE city = 'New Orleans'")
            ).fetchone()

            if not loc_exists:
                conn.execute(text(
                    "INSERT INTO location (location_id, city, latitude, longitude, timezone) "
                    "VALUES (1, 'New Orleans', 29.9547, -90.0751, 'America/Chicago')"
                ))
                logger.info("Dimension Seeding Block: Initialized master reference for 'New Orleans' inside 'location' table.")

        # Step 2: Formulating Parent Fact Frame Fields matching database schemas ('climate_data')
        climate_fact = daily_df.copy().reset_index()
        climate_fact = climate_fact.rename(
            columns={
                "date": "record_date",
                "temp_min_f": "temp_min",
                "temp_max_f": "temp_max",
                "temp_mean_f": "temp_mean",
                "precipitation_inches": "precipitation_sum",
                "rain_inches": "rain_sum",
                "humidity_mean_pct": "humidity_mean",
                "wind_speed_max_mph": "wind_speed_max",
                "cloud_cover_pct": "cloud_cover_mean",
                "solar_radiation_mj": "shortwave_radiation_sum",
                "weather_category_code": "weather_code"
            }
        )
        climate_fact["location_id"] = 1

        sql_climate_fields = [
            "location_id", "record_date", "temp_min", "temp_max", "temp_mean",
            "precipitation_sum", "rain_sum", "humidity_mean", "wind_speed_max",
            "cloud_cover_mean", "shortwave_radiation_sum", "weather_code"
        ]
        climate_fact = climate_fact[sql_climate_fields]

        # Step 3: Formulating Dependent Child Fact Frame Fields matching database schemas ('recommendation')
        rec_fact = rec_df.copy().reset_index()
        rec_fact = rec_fact.rename(
            columns={
                "date": "record_date",
                "comfort_score": "suitability_score",
                "recommended_activities": "reason_summary"
            }
        )

        # Step 4: Loading Target Warehouses via explicit Atomic Transaction blocks
        with engine.begin() as conn:
            # 4.1 Sequenced cascading table truncation to bypass foreign key block constraint faults
            conn.execute(text("TRUNCATE TABLE recommendation RESTART IDENTITY CASCADE;"))
            conn.execute(text("TRUNCATE TABLE climate_data RESTART IDENTITY CASCADE;"))
            logger.info("Database transaction isolation lock acquired. Target warehouse entities truncated.")

            # 4.2 Persisting structured records into the primary parent fact table
            climate_fact.to_sql("climate_data", conn, if_exists="append", index=False)
            logger.info("Successfully populated database entity target: 'climate_data'.")

            # 4.3 Programmatic retrieval of auto-incremented SERIAL climate_id metrics generated in DB
            db_id_map = pd.read_sql("SELECT climate_id, record_date FROM climate_data", conn)
            db_id_map["record_date"] = pd.to_datetime(db_id_map["record_date"])
            rec_fact["record_date"] = pd.to_datetime(rec_fact["record_date"])

            # 4.4 Mapping backend surrogate foreign keys dynamically using logical time keys
            rec_fact = rec_fact.merge(db_id_map, on="record_date", how="inner")
            rec_fact["activity_id"] = 1

            sql_rec_fields = ["climate_id", "activity_id", "suitability_score", "reason_summary"]
            final_rec_db = rec_fact[sql_rec_fields]

            # 4.5 Persisting dependent metrics into the structured child fact table
            final_rec_db.to_sql("recommendation", conn, if_exists="append", index=False)
            logger.info("Successfully populated database entity target: 'recommendation'.")

        logger.info("=== Relational Database Warehouse Storage Pipelines Executed Successfully ===")

    except Exception as error:

        logger.exception("Data warehouse loader process tree collapsed due to relational anomalies.")
        raise RuntimeError("Relational persistence engine mapping operation failed against target catalog constraints.") from error


# ===========================================================================
# COMPONENT 6: LOGGING & ERROR HANDLING — PIPELINE ORCHESTRATOR
# ===========================================================================
def main() -> None:
    """
    Main execution pipeline orchestrator managing execution state transitions.
    Wraps full workflows inside high-level exception trees to handle terminal failures cleanly.
    """
    try:
        logger.info("=== Executing Orchestration Chain: New Orleans Climate Analytical Pipeline ===")

        raw_response = extract_climate_data()
        validate_raw_response(raw_response)

        daily_df = clean_and_normalize_climate(raw_response)
        lookup_df = build_weather_category_lookup()
        daily_df = enrich_with_weather_descriptions(daily_df, lookup_df)


        validate_clean_climate(daily_df)


        weekly_df = build_weekly_aggregation(daily_df)
        recommendations_df = generate_activity_recommendations(daily_df)


        load_csv_outputs(daily_df, weekly_df, recommendations_df)
        load_postgresql_outputs(daily_df, weekly_df, recommendations_df)

        logger.info("Orchestration sequence completed successfully with zero terminal errors.")
        logger.info("Metrics Summary -> Operational Daily Rows: %s", len(daily_df))
        logger.info("Metrics Summary -> Aggregate Weekly Rows: %s", len(weekly_df))
        logger.info("Metrics Summary -> Recommendation Analytical Rows: %s", len(recommendations_df))

    except Exception:
        logger.exception("Pipeline master orchestrator encountered terminal panic state.")
        raise


if __name__ == "__main__":
    main()
